### ISSUE TITLE
Questions about handover simulation in Sim5G

### ISSUE THREAD

**Issue by Alpenbelieve** [Unipisa/Simu5G#1]
Hi, I'm a student and my research area is about handover in 5G.

Sim5G is an excellent work :smile: , and I'm interested in using it to simulate UE's handover process between two 5G BSs.

But the problem is that I can't find any tutorials or guides about simulating handover process in Sim5G.

Is there any hints or suggestions? Thanks a lot ! ❤️ 

(ps: I've installed Simu5G-Cars PnP VM and the simulation example runs well on my computer, but I am not yet proficient in the use of OMNeT++ and Veins 😣 )

**Comment by giovanninardini** [comment]
You can take a look at the simulation example included in folder simulations/NR/dualConnectivity_multicell.
It contains scenarios with UEs performing handover, so you can learn how to configure parameters for your own scenario.

**Comment by Alpenbelieve** [comment]
Thanks!  I'll take a closer look at that and have a try  : )
