### ISSUE TITLE
Couldn't make Simu5G in Ubuntu 

### ISSUE THREAD

**Issue by edadilann** [Unipisa/Simu5G#10]
Hello, I'm trying to install the new version of Omnet on my virtual machine, but when I type the make command, I get an error like the one below.I read your reply to someone who had the same problem as me. I tried what you said but I keep getting the same error.

Makefile:61: Makefile.inc: No such file or directory
make: *** No rule to make target 'Makefile.inc'.  Stop.

**Comment by giovanninardini** [comment]
Hello,
this is not related to Simu5G, so this is not the right place to ask this question (and therefore I will close this issue).

Anyway, please make sure you are following the correct workflow for building OMNeT++: 

```
. setenv
./configure
make
```

Check the section of the OMNeT++ install guide related to your OS.

Best regards.
Giovanni
