### ISSUE TITLE
Question about integrate Simu5G with SDR.

### ISSUE THREAD

**Issue by CODEMIRI** [Unipisa/Simu5G#100]
Hi Dear All,
it is possible to get I/Q Sample from the physical layer in Simu5G and transfer this sample by tcp/ip protocol to SDR like USRP and transmit NR physical channel like PDSCH over the air?

**Comment by giovanninardini** [comment]
Hello,

I do not think it is possible with Simu5G as it implements an abstraction of the physical layer, rather than simulating all the symbols transmitted over the air.

Best regards.
Giovanni
