### ISSUE TITLE
Question about using Simu5G in emulated mode like INET

### ISSUE THREAD

**Issue by TheHupfdole857** [Unipisa/Simu5G#102]
Hello,
I would like to generate some V2V messages and send them via the NR-Stack - provided by Simu5G - to another client over a real network (ethernet or 5G). INET provides a mode called "emulated mode" that is used to test simulated stuff with a real physical network but it has no 5G functionality. Can Simu5G also be used with a real network in an "emulated" mode?

**Comment by giovanninardini** [comment]
Hello,

yes, it can.
See the “emulation” folder for some examples. You can also refer to [this paper](https://ieeexplore.ieee.org/document/9591605) and [this paper](https://www.sciencedirect.com/science/article/abs/pii/S1569190X22001691?via%3Dihub) for more information.

Best regards.
Giovanni
