### ISSUE TITLE
Number of component carrier allowed per gNB in Simu5G

### ISSUE THREAD

**Issue by SawadaSyahmi** [Unipisa/Simu5G#105]
Hi developers,

I am wondering about the number of component carrier that I set per gNB. I have tried to create more than 2 component carrier but failed.

`############### CA configuration ################
*.carrierAggregation.numComponentCarriers = 3
*.carrierAggregation.componentCarrier[0].carrierFrequency = ${carrierFreq0=2GHz}
*.carrierAggregation.componentCarrier[0].numBands = ${carrierBands0=6}
*.carrierAggregation.componentCarrier[1].carrierFrequency = ${carrierFreq1=6GHz}
*.carrierAggregation.componentCarrier[1].numBands = ${carrierBands1=6}
*.carrierAggregation.componentCarrier[2].carrierFrequency = ${carrierFreq2=700MHz}
*.carrierAggregation.componentCarrier[2].numBands = ${carrierBands2=6}

*.masterEnb.cellularNic.numCarriers = 3
*.masterEnb.cellularNic.channelModel[0].componentCarrierIndex = 0
*.masterEnb.cellularNic.channelModel[1].componentCarrierIndex = 1    
*.masterEnb.cellularNic.channelModel[2].componentCarrierIndex = 2
*.secondaryGnb.cellularNic.channelModel[0].componentCarrierIndex = ${nrCarrier=0}

*.ue[*].cellularNic.numCarriers = 2
*.ue[*].cellularNic.channelModel[0].componentCarrierIndex = 0
*.ue[*].cellularNic.channelModel[1].componentCarrierIndex = 1  
*.ue[*].cellularNic.channelModel[2].componentCarrierIndex = 2    
*.ue[*].cellularNic.nrChannelModel[0].componentCarrierIndex = ${nrCarrier}`

However, there are no signal received from the third channel model. 
![image](https://user-images.githubusercontent.com/86639833/212462699-1b3d84f3-210c-42b9-bed0-a1ccd14dfef4.png)

How can i add more than 2 channel model?

Thank you for your attention.

**Comment by notitle420** [comment]
Hi SawadaSyahmi

i also have the this problem. how did you solve it?
