### ISSUE TITLE
Problem with dynamic UEs

### ISSUE THREAD

**Issue by vinis-caixe** [Unipisa/Simu5G#110]
Hello everyone,
I am having problem creating dynamic UEs in a network similar to SingleCell_Standalone. When a UE is created (e.g. ue0) its IP address is marked as <unspec> and it does not receive any packets. On issue #24 it says: 
"you can directly set the module name of the receiving as the destination address of the server application. The IPv4NetworkConfigurator will automatically translate it to an IP address.". 
However when I do that (e.g. *.server.app[0].destAddress = "ue0") I receive the following error: 
"L3AddressResolver: Cannot resolve address `ue0' -- in module (VoIPSender) UrbanMacro5G.server.app[0] (id=34), at t=0.02s"
Thanks in advance.

**Comment by giovanninardini** [comment]
Hello,

have you tried to use "ue[0]" (with brackets)?

**Comment by vinis-caixe** [comment]
I did, but now I get the following error: "Module not found on path 'UrbanMacro5G.ue[0].interfaceTable' defined by par 'UrbanMacro5G.ue[0].ipv4.configurator.interfaceTableModule' -- in module (inet::Ipv4NodeConfigurator) UrbanMacro5G.ue[0].ipv4.configurator (id=267), at t=0s".
I checked the ue[0] and it has a interfaceTable module.

**Comment by gehirndienst** [comment]
I experience the same problem since some time: if I use simu5g's VoIPSender/Receiver combination when server = receiver, ue[0] = sender, it works, when it is flipped - simulation is stuck on initialization phase.

**Comment by giovanninardini** [comment]
> I experience the same problem since some time: if I use simu5g's VoIPSender/Receiver combination when server = receiver, ue[0] = sender, it works, when it is flipped - simulation is stuck on initialization phase.
> 
> And I can clearly see what is happening: server sends a datagram to the ue[0] with a correct destination address, but a router returns ICMP-error-type3, which means that destination is unknown, however server's app was able to correctly resolve address from the module's name ue[0]

do you experience this when creating a UE dynamically? If so, I assume the UE is using "HostAutoConfigurator" as configurator module within the UE (like the NRCar module). In that case, you need to make sure that the xml file used by network configurator module is set correctly, i.e. the UEs have been set with IP addresses from the same subnet as the gNodeBs (see the _simulations/NR/cars/demo.xml_ file). By default, UEs with "HostAutoConfigurator" get addresses from the 10.0.0.0/8 subnet.

**Comment by gehirndienst** [comment]
> > I experience the same problem since some time: if I use simu5g's VoIPSender/Receiver combination when server = receiver, ue[0] = sender, it works, when it is flipped - simulation is stuck on initialization phase.
> > And I can clearly see what is happening: server sends a datagram to the ue[0] with a correct destination address, but a router returns ICMP-error-type3, which means that destination is unknown, however server's app was able to correctly resolve address from the module's name ue[0]
> 
> do you experience this when creating a UE dynamically? If so, I assume the UE is using "HostAutoConfigurator" as configurator module within the UE (like the NRCar module). In that case, you need to make sure that the xml file used by network configurator module is set correctly, i.e. the UEs have been set with IP addresses from the same subnet as the gNodeBs (see the _simulations/NR/cars/demo.xml_ file). By default, UEs with "HostAutoConfigurator" get addresses from the 10.0.0.0/8 subnet.

yes, dynamically, my scenario is fully based on NR/cars with more complicated SUMO scenario. I copied demo.xml from your simulation example as well ;-) anyway thanks for a response, I will dig it further

**Comment by vinis-caixe** [comment]
I was not using the "HostAutoConfigurator", after following the example of the cars simulation my problem has been solved.
Thank you very much!
