### ISSUE TITLE
.

### ISSUE THREAD

**Issue by yuvan257** [Unipisa/Simu5G#117]

**Comment by Ali-K-Abbas** [comment]
Dear ,
I faced the same Problem with win 11 then every things worked just fine after I applied Solution in https://github.com/Unipisa/Simu5G/issues/65 , try it and use  omnetpp - 6.0

**Comment by L0rd0fCode** [comment]
I encountered the exact same problem here. @Ali-K-Abbas 's advice does not help unfortunately.

**Comment by L0rd0fCode** [comment]
Went back to windows 10 but the issue is still there. That's a bummer, idk what else to do

**Comment by qiaox123** [comment]
I also met this problem, how to solve it? The version I use is as follows：
windows 11;
omnet++ 6.0
inet 4.4.0
simu5g 1.2.1

**Comment by giovanninardini** [comment]
Could you please try to use the latest Simu5G release 1.2.2 and INET 4.5?

You can download and install both of them directly from the OMNeT+ +IDE: click on "Help" -> "Install simulation models..." and select INET 4.5 and Simu5G 1.2.2.

**Comment by qiaox123** [comment]
> 
but after I use the following version of the software
windows11
omnet++ 6.0.1
inet 4.5
simu5g 1.2.2
The same mistakes remain as before:
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
D:/software/simulation/omnetpp-6.0.1-windows-x86_64/omnetpp-6.0.1/tools/win32.x86_64/mingw64/bin/llvm-ar.exe: error: unable to load '../out/clang-debug/src/libsimu5g_dbg.dll.a': No such file or directory
make[1]: *** [Makefile:424: ../out/clang-debug/src/libsimu5g_dbg.dll] Error 1
make[1]: Leaving directory '/d/simulation_workspace/project1/simu5g/src'
make: *** [Makefile:2: all] Error 2
"make MODE=debug -j16 all" terminated with exit code 2. Build might be incomplete.

**Comment by Dead0utside** [comment]
@qiaox123 Try reinstalling Omnet++ from scratch but whan unpacking it, run your archive manager with admin rights. Also, do not use the default windows archive manager. It turns out, that without admin rights the archiver cannot create some symbolic links when unpacking, therefore Omnet works incorrectly. Might sound like a joke, but that's what helped me at least. After reinstalling Omnet you can download Simu5G directly from the IDE. Should work, wish you best of luck

**Comment by qiaox123** [comment]
> @qiaox123 Try reinstalling Omnet++ from scratch but whan unpacking it, run your archive manager with admin rights. Also, do not use the default windows archive manager. It turns out, that without admin rights the archiver cannot create some symbolic links when unpacking, therefore Omnet works incorrectly. Might sound like a joke, but that's what helped me at least. After reinstalling Omnet you can download Simu5G directly from the IDE. Should work, wish you best of luck

Hello, are you also running on windows11? I have used admin privileges to unzip omnet++, but my error still seems to be unresolved?

**Comment by Dead0utside** [comment]
> > @qiaox123 Try reinstalling Omnet++ from scratch but whan unpacking it, run your archive manager with admin rights. Also, do not use the default windows archive manager. It turns out, that without admin rights the archiver cannot create some symbolic links when unpacking, therefore Omnet works incorrectly. Might sound like a joke, but that's what helped me at least. After reinstalling Omnet you can download Simu5G directly from the IDE. Should work, wish you best of luck
> 
> Hello, are you also running on windows11? I have used admin privileges to unzip omnet++, but my error still seems to be unresolved?

I've been using windows 11 for some time before the issue first appeared. Now that I think about it, it probably appeared after I reinstalled omnet++ on windows 11. Unable to fix it, I had no choice but to go back to windows 10. The issue persisted though. Then I've been trying different things to fix it but nothing helped until I noticed some errors 7-zip was spitting out, something like "unable to create symbolic links, no privilege", though I don't remember precisely. So I changed 7-zip to WinRar, unpacked and installed everything as always and quite surprisingly, everything started working again. So you might as well try using winrar if you aren't. I hope it helps

**Comment by qiaox123** [comment]
> > > @qiaox123 Try reinstalling Omnet++ from scratch but whan unpacking it, run your archive manager with admin rights. Also, do not use the default windows archive manager. It turns out, that without admin rights the archiver cannot create some symbolic links when unpacking, therefore Omnet works incorrectly. Might sound like a joke, but that's what helped me at least. After reinstalling Omnet you can download Simu5G directly from the IDE. Should work, wish you best of luck
> > 
> > 
> > Hello, are you also running on windows11? I have used admin privileges to unzip omnet++, but my error still seems to be unresolved?
> 
> I've been using windows 11 for some time before the issue first appeared. Now that I think about it, it probably appeared after I reinstalled omnet++ on windows 11. Unable to fix it, I had no choice but to go back to windows 10. The issue persisted though. Then I've been trying different things to fix it but nothing helped until I noticed some errors 7-zip was spitting out, something like "unable to create symbolic links, no privilege", though I don't remember precisely. So I changed 7-zip to WinRar, unpacked and installed everything as always and quite surprisingly, everything started working again. So you might as well try using winrar if you aren't. I hope it helps

Thank you for your advice.But I still have not solved, I originally used winRAR, and then I changed to 7z, are not very good, now I guess this problem should be caused by the windows11 system, and after I  change the system to try it. Thank you again

**Comment by shashini-w** [comment]
> Could you please try to use the latest Simu5G release 1.2.2 and INET 4.5?
> 
> You can download and install both of them directly from the OMNeT+ +IDE: click on "Help" -> "Install simulation models..." and select INET 4.5 and Simu5G 1.2.2.

@giovanninardini I tried installing Simu5G 1.2.2 and I am getting a similar error. I have worked with the previous versions of simu5G and they all compiled without any error. 

**My specs :** 
- Windows 10
- OMNeT ++ 6.0.1
-  INET 4.5
- Simu5G 1.2.2
                  
I installed both INET and Simu5G directly from OMNeT. I even tried all the solutions already suggested in issues #6 , #54 and #65 . I tried changing the compiler to gcc as well. I even tried adding the line `LDFLAGS:= $(LDFLAGS) -Wl,--allow-multiple-definition ` under properties->makemake->src->custom but still I keep getting the following error:

```
ld.lld: error: duplicate symbol: non-virtual thunk to inet::Packet::~Packet() defined at ../../inet4.5/src/inet/common/packet/Packet.h:101
 ../out/gcc-debug/src/stack/packetFlowManager/PacketFlowManagerEnb.o defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::SctpClient::socketAvailable(inet::SctpSocket*, inet::Indication*) defined at ../../inet4.5/src/inet/applications/sctpapp/SctpClient.h:83
 ../out/gcc-debug/src/x2/X2AppClient.o defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::MovingMobilityBase::getCurrentAcceleration() defined at ../../inet4.5/src/inet/mobility/base/MovingMobilityBase.h:79
 ../out/gcc-debug/src/mobility/trafficLightMobility/TrafficLightMobility.o defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::MovingMobilityBase::getCurrentAngularAcceleration()  defined at ../../inet4.5/src/inet/mobility/base/MovingMobilityBase.h:83
 ../out/gcc-debug/src/mobility/trafficLightMobility/TrafficLightMobility.o  defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::MobilityBase::getConstraintAreaMax() const defined at ../../inet4.5/src/inet/mobility/base/MobilityBase.h:168
  ../out/gcc-debug/src/mobility/trafficLightMobility/TrafficLightMobility.o  defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::MobilityBase::getConstraintAreaMin() const defined at ../../inet4.5/src/inet/mobility/base/MobilityBase.h:169
 ../out/gcc-debug/src/mobility/trafficLightMobility/TrafficLightMobility.o  defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::MobilityBase::getId() const defined at ../../inet4.5/src/inet/mobility/base/MobilityBase.h:83
 ../out/gcc-debug/src/mobility/trafficLightMobility/TrafficLightMobility.o defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::LinearMobility::getMaxSpeed() const  defined at ../../inet4.5/src/inet/mobility/single/LinearMobility.h:38
../out/gcc-debug/src/mobility/trafficLightMobility/TrafficLightMobility.o defined at libINET_dbg.dll

ld.lld: error: duplicate symbol: non-virtual thunk to inet::Chunk::getRegionTags()  defined at ../../inet4.5/src/inet/common/packet/chunk/Chunk.h:691
 ../out/gcc-debug/src/apps/mecRequestResponseApp/MecRequestApp.o  defined at libINET_dbg.dll
collect2.exe: error: ld returned 1 exit status
C:/Users/ultras/Desktop/omnetpp-6.0.1/tools/win32.x86_64/mingw64/bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libsimu5g_dbg.dll.a': No such file or directory
make[1]: *** [Makefile:424: ../out/gcc-debug/src/libsimu5g_dbg.dll] Error 1
make[1]: Leaving directory '/c/Users/ultras/Desktop/omnetpp-6.0.1/samples/simu5g/src'
make: *** [Makefile:2: all] Error 2
"make MODE=debug -j8 all" terminated with exit code 2. Build might be incomplete.

13:35:48 Build Failed. 2 errors, 85 warnings. (took 2m:28s.652ms)
```

**Comment by ToThichCa** [comment]
Hello,
I have also followed the previous suggested solutions like you but the problem is still not solved. Did you find any solution

**Comment by avarga** [comment]
Have you tried opp_env? https://omnetpp.org/opp_env
