### ISSUE TITLE
Network creation step fails with segmentation fault

### ISSUE THREAD

**Issue by dekaio** [Unipisa/Simu5G#121]
Debugger points to [MacForwardingTableConfigurator.cc] file, in the extendConfiguration function, in the line interfacename = firstInterface->networkInterface->getInterfaceName().

The UE was modified, and an ethernet port was added to connect it to an Ethernet network.
The network consists of BS---UE---EthernetSwitch---StandardHost
However, a segmentation fault is thrown at the network creation stage.
The error gets thrown at the switch. 
What could be the potential reason why an error is thrown in this particular line?
Please see the screenshot of the debug flow below.
![223487791-2ec5aad1-118f-48db-8675-80a5ce5976ec](https://user-images.githubusercontent.com/47273651/224164416-0a15b746-f328-4651-8765-6bfbd852297b.png)

**Comment by giovanninardini** [comment]
Hello,
this error seems to appear in the INET code. INET developers could probably answer your question better than I.
