### ISSUE TITLE
numBands in 5G

### ISSUE THREAD

**Issue by Parvaaaa** [Unipisa/Simu5G#125]
Hello,

I would like to define some carrier aggregation related parameters in my ini file. One of them is numBands, which is configurable using this line: "*.carrierAggregation.componentCarrier[0].numBands = ". How should I calculate the numBands in a 5G network for bandwidth of 100 MHz and subcarrier spacing of 30 KHz? The answer which is given here #29 is true only for LTE, right?  
Since in 5G, the capacity of each resource block differs according to the subcarrier spacing, how should I calculate the numBands?

Thank you in advance.

**Comment by Jiacheng188** [comment]
Hello, may be this [blog](http://www.sharetechnote.com/html/5G/5G_FR_Bandwidth.html#Spectrum_and_Bandwidth) on _sharetechnote_ can help you.
Pay attention to the terms _channel bandwidth_ and _transmission bandwidth_.
A brief figure is shown below.
![image](https://user-images.githubusercontent.com/78731659/224925706-85b251f0-9fca-4882-9d53-5aa95821e1ec.png)
