### ISSUE TITLE
Ethernet interface for gNB

### ISSUE THREAD

**Issue by dekaio** [Unipisa/Simu5G#126]
Hi,

A Simu5G gNB has a cellularNIC, PPP, and X2 interface.
Is it correct protocol-wise to add an ethernet interface to a gNB?

Thanks

**Comment by giovanninardini** [comment]
Hello,

I am not sure what you mean with “protocol-wise”.
Anyway, you can add an Ethernet interface to a gNB for sure, like in any other network module in OMNeT.

Giovanni

**Comment by giovanninardini** [comment]
Hello,

I am not sure what you mean by “protocol-wise”.
Anyway, you can add an Ethernet interface to a gNB for sure, as in any other network module in OMNeT.

Giovanni

**Comment by dekaio** [comment]
Thank you
