### ISSUE TITLE
UE retransmission issue

### ISSUE THREAD

**Issue by Jiacheng188** [Unipisa/Simu5G#128]
Dear author,
the code in _NRMacUE::handleSelfMessage_ indicates that if there is no retransmission, the normal scheduling can be performed.
I wonder if the size of the MAC PDU needed to be retransmitted and the current granted bytes are considered in the retransmission procedure?

**Comment by giovanninardini** [comment]
I would say that the retransmission procedure is carried out like the normal scheduling procedure. The gNB's scheduler assigns a grant whose size depends on the MAC PDU size to be retransmitted and the latest CQI.

**Comment by Jiacheng188** [comment]
Thank you!
