### ISSUE TITLE
LTE APP Delay

### ISSUE THREAD

**Issue by wggegshjg** [Unipisa/Simu5G#129]
Dear author
I was measuring 4G end-to-end latency and found that a very small packet had a latency of 5ms

*.ue11.app[*].typename = "AlertReceiver"

*.server.app[*].destAddress = "ue11" 
*.server.app[*].packetSize=100
*.server.app[*].localPort = 3088+ancestorIndex(0) 
*.server.app[*].typename = "AlertSender"
*.server.app[*].startTime = 0.01s

INFO:AlertReceiver::handleMessage - Packet received: SeqNo[12] Delay[0.005]
When I set the packet size to 1000B, the delay is also 5ms.

I found that the minimum latency is 5 ms. What is the reason for this?

**Comment by giovanninardini** [comment]
Hello,

I guess you are transmitting a packet in the downlink with numerology 0, and that your packet fits one single MAC PDU in both cases (100B and 1000B). This means that the gNB can schedule your data in one TTI only. Then, when the transmission is performed, at the receiver side the packet needs some time to be "evaluated". In Simu5G, we assume 4 TTIs to decode the airframe at the receiver side (the transmitter expects to receive an ACK/NACK after 4 ms). This results in 4 additonal milliseconds in the total delay "budget".

**Comment by wggegshjg** [comment]
It can be understood as follows: if i=2, the additional delay is 4TTI=1ms


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Unipisa/Simu5G"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Unipisa/Simu5G] LTE APP Delay (Issue #129)





 
Closed #129 as completed.
