### ISSUE TITLE
Question about UPF TrafficFlowFilter Connection to Ethernet gate

### ISSUE THREAD

**Issue by dekaio** [Unipisa/Simu5G#135]
Hi,

In the current model, the UPF Traffic flow filter is connected only to the pppFilterGate. 
May I know if connecting the Traffic Flow Filter to the ethernet interface is correct?

Thank you.

**Comment by giovanninardini** [comment]
The _trafficFlowFilter_ module is the module receiving the packets from the Internet domain (i.e., from the outside of the 5G network domain). 
In the UPF module, the _pppFilterGate_ is the gate connected to the Internet domain, so that is why the _trafficFlowFilter_ is connected to it.

**Comment by giovanninardini** [comment]
I think you can do it, yes.

**Comment by dekaio** [comment]
Thanks
