### ISSUE TITLE
Question regarding modifying configurations

### ISSUE THREAD

**Issue by Dead0utside** [Unipisa/Simu5G#136]
Greetings,
I am totally new to omnet++ and I do not have much time to learn everything from scratch, that is the reason I'm writing this issue. Is it possible to reconfigure an existing sample (say standalone) so that it would simulate a video stream instead of VoIP? Also I will probably have further questions as I proceed with my bachelor's project. For now I would appreciate an ansewer for this question. Have a good day

**Comment by giovanninardini** [comment]
Of course it is possible.
Take a look at [this](https://github.com/Unipisa/Simu5G/blob/master/simulations/LTE/demo/omnetpp.ini) omnetpp.ini [Config VideoStreaming]. It is for an LTE simulation, but the application part is valid also for 5G simulations.
