### ISSUE TITLE
Install Veins 5.2 and Simu5g 1.2.1

### ISSUE THREAD

**Issue by CODEMIRI** [Unipisa/Simu5G#140]
Hi everyone,
I installed omnet++6.0 and then installed INET4.4.
After that I wanted to install Simu5g1.2.1 then I installed it based on below instructions:

I followed with instructions:
****
Extract the downloaded Simu5G tarball next to the "inet4.4" directory (i.e. into your workspace directory, if you are using the IDE).
Start the IDE, and ensure that the 'inet4.4' project is open and correctly built.
Import the project using: File | Import | General | Existing projects into Workspace. Then select the workspace dir as the root directory, and be sure NOT to check the "Copy projects into workspace" box. Click Finish.
You can build the project by pressing CTRL-B (Project | Build all)

Start the OMNeT++ IDE and open your Simu5G workspace
Import the project using: File | Import | General | Existing projects into Workspace. Then select your workspace directory, i.e. the one including Simu5G, inet4.4, and Veins folders. Tick the "Search for nested projects" box and select "veins" and "veins_inet" projects. Click Finish.
In the project explorer, right-click on the "Simu5G" folder | Properties | Project References. Tick the "veins_inet" box (do not tick the "veins" folder. Click OK.
In the project explorer, right-click on the "Simu5G" folder | Properties | OMNeT++ | Project Features. Tick the "Simu5G Cars" box. Click OK.
Build the project by pressing CTRL-B (or Project | Build all).
I get the (fatal error: 'inet/networklayer/common/L3AddressResolver.h')
and sometimes I get cannot find -lveins_inet.
would you please help me to install veins beside simu5g?

**Comment by NamaeN0Nai** [comment]
I am running into the same issue as well on a mac machine.
veins will compile if you add it without ticking the "Search for nested projects" box. However, by doing so you won't be able to tick the "veins_inet" in projects' properties.
Anyone knows how to solve this issue?

**Comment by giovanninardini** [comment]
When importing Veins, please tick the "Search for nested projects" box and also tick the "copy projects into workspace" box. This will copy the _veins_inet_ subproject into the "main" workspace folder and, somehow, this will enable the "veins_inet" box in the project properties.
