### ISSUE TITLE
Same delay in VoIP

### ISSUE THREAD

**Issue by Clau4github** [Unipisa/Simu5G#142]
Dear all,

I have implemented a VoIP simple scenario following the example in NR/Stand Alone. The issue is that the end-to-end delay is always the same. Is there a way to modify the end to end delay by modifying different parameters of the network? The transmission delay, the processing delay or the queuing delay ?

Thanks in advance.

**Comment by giovanninardini** [comment]
Hello,
the end-to-end delay depends on the network capacity and traffic load. In the standalone example, you have only one user, very close to the base station - i.e., the UE is in the best possible conditions.
You can try to increase the number of UEs and the amount of traffic they transmit, or you can reduce the number of bands available at the gNB (i.e., reduce the available capacity)

Best regards.
Giovanni

**Comment by Clau4github** [comment]
Hello Giovanni, 

Thank you so much for your response. 
I understand. But is it possible to simulate any time of processing delay inside the routers or the nodeB ? The other option could be to simulate some transportation delay. Is it possible to simulate a different transmission distance from the NodeB to the router or similar?

Thanks in advance,

Best regards, 

Claudia

**Comment by giovanninardini** [comment]
Hello,

yes, that is possible.

- First option (quick but not-so-elegant): modify the length of the Ethernet cable in the network NED file, e.g.: `iUpf.pppg++ <--> Eth10G {length = 10000km; } <--> gnb.ppp;`

- Second option: use one the ned.DatarateChannel and customize its parameters, e.g.: `iUpf.pppg++ <--> DatarateChannel { datarate=10Gbps; delay = 1s; } <--> gnb.ppp;`
- In this case remember to import the NED module, using `import ned.DatarateChannel` at the beginning of the NED file 

Best regards.
Giovanni

**Comment by Clau4github** [comment]
Hello,
Thanks for your answer. One additional question though, is it possible to make the delay random after any given time ? 

I mean, for the second option:  use one the ned.DatarateChannel and customize its parameters, e.g.: iUpf.pppg++ <--> DatarateChannel { datarate=10Gbps; **_delay = 1s_**; } <--> gnb.ppp; 
What I would like to do is to include a random range instead of a fixed value for the delay, and that every given time, the random value is calculated again. Could it be done in that way? 

Thanks a lot for your answers and comments. 
Best Regards, 
Claudia
