### ISSUE TITLE
SS-RSRP in Simu5g

### ISSUE THREAD

**Issue by Parvaaaa** [Unipisa/Simu5G#143]
Hello all, 

Does Simu5g calculate the SS-RSRP and accordingly SS-SINR in LteRealisticChannelModel.cc or the RS-RSRP and RS-SINR? 
If SS, then does it mean that the PBCH block is implemented?

Thank you in advance.

Parva

**Comment by giovanninardini** [comment]
Since Simu5G does not model the physical layer in a detail as deep as the resource elements, Simu5G just computes an RSRP (hence, a SINR) that does not depend on which RE the signal is sent (in other words, reference signals are not modelled)
