### ISSUE TITLE
Simulate a processing time

### ISSUE THREAD

**Issue by zazim13** [Unipisa/Simu5G#146]
Hi, 
1. I am trying to simulate a processing time to make my MecApp more realistic. I would like my mecApp to actually consume simulation time. I saw in [this](https://arxiv.org/abs/2203.13511)  paper that I can call compute(N)  but I cannot find this function used.

2. And also I would like to confirm the behaviour of the mecApp when there are multiple requests coming from the UE, in the case where each request triggers some computations that consume some simulation time( thanks to comput(N) ). When the mecApp has already scheduled the computation time for a request, if it receives a new requests, 
Is the computation time of the previous request delayed ? 
will the mecApp take into account the remaining computation resources ? 
What happens when there are no more resources available ? 

Sincerly
Hakim

**Comment by giovanninardini** [comment]
Hello,

1. please see the function `VirtualisationInfrastructureManager::calculateProcessingTime()`

2. the current implementation of  `VirtualisationInfrastructureManager::calculateProcessingTime()` just returns 
a "delay" that considers the number of instructions to be executed by the MecApp invoking the function itself and the amount of resources allocated to the MecApp (see the code of the function). This means that previous processing time requests are not affected.

**Comment by zazim13** [comment]
Hi, Thank you for your answer.
