### ISSUE TITLE
Horizontal Handover Decision

### ISSUE THREAD

**Issue by ChristophPargfrieder** [Unipisa/Simu5G#147]
Hey,

I am quite new to OMNET++ and Simu5G and I want to implement my own algorithms for horizontal handovers. I have set up a scenario using SUMO and several gNBs (inspired by the cars and standalone_multicell example). Now, I want to implement my handover strategies, but I am quite lost where to start.

Where in the code exactly does the handover decision happen? I think this would be then an interesting starting point.

Best Regards,
Christoph

**Comment by giovanninardini** [comment]
Hello,

please take a look at the `LtePhyUe::handoverHandler()` function ([here](https://github.com/Unipisa/Simu5G/blob/4625689909f9c13ae6461087098de5f5459c932a/src/stack/phy/layer/LtePhyUe.cc#L252)). 
That is the function that, for each gNB, computes the strength of the received power at the UE and selects the gNB with the higher value.

Best regards.
Giovanni

**Comment by ChristophPargfrieder** [comment]
Thank you very much for the reply!

I am just looking into the code and try to understand how this works. The handoverHandler() is called in handleAirFrame() when the frametype of the incoming message is HANDOVERPKT. What component sends this message to the UE? And what event triggers that component to send this message? Are these broadcast messages sent periodically from each gNBs?
