### ISSUE TITLE
RNI service initialisation error

### ISSUE THREAD

**Issue by hcr-git** [Unipisa/Simu5G#151]
Hello,

we are configuring the RNIService in the emulation example: emulations/mec/extUeAppMecApp. For now, we are substituting the Location service configuration by the RNI service configuration in omnetpp.ini file (the objective is to change UeApp.py and MecApp.py in order to use RNI):

[in omnetpp.ini file]
##---- RNI service
*.mecHost1.mecPlatform.mecService[0].typename = "RNIService"
*.mecHost1.mecPlatform.mecService[0].localAddress = "mecHost1.virtualisationInfrastructure"
*.mecHost1.mecPlatform.mecService[0].localPort = 10020
*.mecHost*.mecPlatform.mecService[0].rng-0 = 1 # request service time
*.mecHost*.mecPlatform.mecService[0].rng-1 = 2 # subscription service time
*.mecHost*.mecPlatform.mecService[0].requestServiceTime = 20us
*.mecHost*.mecPlatform.mecService[0].subscriptionServiceTime = 11us
##---- RNI service

When executing the emulation in the command line, we got the following error:

[execution results]
......
Setting up Cmdenv...

Loading NED files from /home/simu5g/Simulador/Setup/Simu5G/simulations:  20
Loading NED files from /home/simu5g/Simulador/Setup/Simu5G/emulation:  8
Loading NED files from /home/simu5g/Simulador/Setup/Simu5G/src:  88
Loading NED files from /home/simu5g/Simulador/Setup/inet4.4/src:  1166

Preparing for running configuration ExtUeAppMecApp, run #0...
Assigned runID=ExtUeAppMecApp-0-20230511-18:43:44-1298417
Setting up network "RNITest"...
Recording eventlog to file `results/ExtUeAppMecApp-#0.elog'...
Initializing...

<!> Error: check_and_cast(): Cannot cast nullptr to type 'BaseStationStatsCollector *' -- in module (RNIService) RNITest.mecHost1.mecPlatform.mecService[0] (id=253), during network initialization

....

We are using Simu5G 1.2.1.

Can you help us?

Thank you,
Helena Rodrigues

**Comment by giovanninardini** [comment]
Hello,

please try to add the parameter `**.hasRNISupport = true` to your INI file and see if that solves the problem.

Best regards.
Giovanni

**Comment by hcr-git** [comment]
Hello, 

yes, it solved the problem.

thank you,
Helena Rodrigues
