### ISSUE TITLE
Running a Simu5G emulation with CAR element

### ISSUE THREAD

**Issue by hcr-git** [Unipisa/Simu5G#155]
Hi,

we are building a Simu5G emulation that builds on a car mobility model (using SUMO and VEINS). We are building it, for now, on top of the emulations/mec/extMecAppUeApp emulation provided with Simu5G 1.2.1.

We want the real client app to connect to the Device App on the CAR element (previously configured in omnetpp-ini file). We built the CAR element mrt file as the UE mrt file.

The simulation stops at event 18 with the following error (even before we have started UeApp.py - real client app):

Simulation batch
Finished with Error
<!> Error: Implicit data reinterpretation via chunk serialization/deserialization (inet::ArpPacket -> inet::Ipv4Header) is disabled to prevent unexpected behavior due to reinterpretation and unpredictable performance degradation due to overhead (you may consider changing the Chunk::enableImplicitChunkSerialization flag or passing the PF_ALLOW_SERIALIZATION flag) -- in module (IP2Nic) OpenRTiSTEmulation.car.cellularNic.ip2nic (id=355), at t=0s, event #18

Can you help us on this issue?
Thank you,
Helena Rodrigues

##############
The emulation complete output is:

Starting...

$ cd /home/simu5g/Simulador/Setup/Simu5G/emulation/mec/OpenRTiSTEmulation
$ opp_run -r 0 -m -u Cmdenv -c General -n ../..:../../../simulations:../../../src:../../../../inet4.4/examples:../../../../inet4.4/showcases:../../../../inet4.4/src:../../../../inet4.4/tests/validation:../../../../inet4.4/tests/networks:../../../../inet4.4/tutorials:../../../../veins_inet/src/veins_inet:../../../../veins_inet/examples/veins_inet:../../../../veins-veins-5.2/examples/veins:../../../../veins-veins-5.2/src/veins -x inet.common.selfdoc;inet.linklayer.configurator.gatescheduling.z3;inet.showcases.visualizer.osg;inet.examples.emulation;inet.showcases.emulation;inet.transportlayer.tcp_lwip;inet.applications.voipstream;inet.visualizer.osg;inet.examples.voipstream --image-path=../../../images:../../../../inet4.4/images:../../../../veins_inet/images:../../../../veins-veins-5.2/images -l ../../../src/simu5g -l ../../../../inet4.4/src/INET -l ../../../../veins_inet/src/veins_inet -l ../../../../veins-veins-5.2/src/veins omnetpp.ini

OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.0.1, build: 220831-e4f07d04b8, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Cmdenv...

Loading NED files from ../..:  9
Loading NED files from ../../../simulations:  21
Loading NED files from ../../../src:  88
Loading NED files from ../../../../inet4.4/examples:  176
Loading NED files from ../../../../inet4.4/showcases:  69
Loading NED files from ../../../../inet4.4/src:  1132
Loading NED files from ../../../../inet4.4/tests/validation:  5
Loading NED files from ../../../../inet4.4/tests/networks:  6
Loading NED files from ../../../../inet4.4/tutorials:  20
Loading NED files from ../../../../veins_inet/src/veins_inet:  8
Loading NED files from ../../../../veins_inet/examples/veins_inet:  2
Loading NED files from ../../../../veins-veins-5.2/examples/veins:  1
Loading NED files from ../../../../veins-veins-5.2/src/veins:  43

Preparing for running configuration General, run #0...
Scenario: $u=0, $numRbs=50, $repetition=0
Assigned runID=General-0-20230522-13:31:33-1559532
Setting up network "OpenRTiSTEmulation"...
Initializing...

Running simulation...
** Event #0   t=0   Elapsed: 2.6e-05s (0m 00s)  0% completed  (0% total)
     Speed:     ev/sec=0   simsec/sec=0   ev/simsec=0
     Messages:  created: 165   present: 163   in FES: 27
** Event #18   t=0   Elapsed: 0.415923s (0m 00s)  0% completed  (0% total)
     Speed:     ev/sec=43.2792   simsec/sec=0   ev/simsec=0
     Messages:  created: 214   present: 197   in FES: 20

<!> Error: Implicit data reinterpretation via chunk serialization/deserialization (inet::ArpPacket -> inet::Ipv4Header) is disabled to prevent unexpected behavior due to reinterpretation and unpredictable performance degradation due to overhead (you may consider changing the Chunk::enableImplicitChunkSerialization flag or passing the PF_ALLOW_SERIALIZATION flag) -- in module (IP2Nic) OpenRTiSTEmulation.car.cellularNic.ip2nic (id=355), at t=0s, event #18
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.iUpf.ipv4.routingTable: interfaceStateChanged ppp1 ID:102 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.2.2/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.upf.ipv4.routingTable: interfaceStateChanged ppp0 ID:101 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.2.1/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.ualcmp.ipv4.routingTable: interfaceStateChanged pppIf ID:100 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.3.2/24 mcastgrps:224.0.0.1} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.upf.ipv4.routingTable: interfaceStateChanged pppIf ID:102 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.3.1/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	Clear all sockets
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.gNodeB1.ipv4.routingTable: interfaceStateChanged pppIf ID:101 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.1.2/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.iUpf.ipv4.routingTable: interfaceStateChanged ppp0 ID:101 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.1.1/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.mecHost1.upf_mec.ipv4.routingTable: interfaceStateChanged ppp0 ID:101 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.4.2/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.iUpf.ipv4.routingTable: interfaceStateChanged ppp2 ID:103 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.4.1/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	Clear all sockets
[INFO]	Clear all sockets
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.mecHost1.upf_mec.ipv4.routingTable: interfaceStateChanged pppIf ID:102 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.5.1/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	** Signal at T=0 to OpenRTiSTEmulation.mecHost1.virtualisationInfrastructure.ipv4.routingTable: interfaceStateChanged pppIf0 ID:100 MTU:1500 UP NOCARRIER MULTICAST POINTTOPOINT macAddr:n/a Ipv4:{inet_addr:10.0.5.2/24 mcastgrps:224.0.0.1,224.0.0.2} changed field: 0
[INFO]	 
[INFO]	Clear all sockets
terminate called after throwing an instance of 'omnetpp::cRuntimeError'
  what():  No such gate or gate vector: 'upperLayerOut'

Simulation terminated with exit code: 86
Working directory: /home/simu5g/Simulador/Setup/Simu5G/emulation/mec/OpenRTiSTEmulation
Command line: opp_run -r 0 -m -u Cmdenv -c General -n ../..:../../../simulations:../../../src:../../../../inet4.4/examples:../../../../inet4.4/showcases:../../../../inet4.4/src:../../../../inet4.4/tests/validation:../../../../inet4.4/tests/networks:../../../../inet4.4/tutorials:../../../../veins_inet/src/veins_inet:../../../../veins_inet/examples/veins_inet:../../../../veins-veins-5.2/examples/veins:../../../../veins-veins-5.2/src/veins -x inet.common.selfdoc;inet.linklayer.configurator.gatescheduling.z3;inet.showcases.visualizer.osg;inet.examples.emulation;inet.showcases.emulation;inet.transportlayer.tcp_lwip;inet.applications.voipstream;inet.visualizer.osg;inet.examples.voipstream --image-path=../../../images:../../../../inet4.4/images:../../../../veins_inet/images:../../../../veins-veins-5.2/images -l ../../../src/simu5g -l ../../../../inet4.4/src/INET -l ../../../../veins_inet/src/veins_inet -l ../../../../veins-veins-5.2/src/veins omnetpp.ini

Environment variables:
PATH=/home/simu5g/Simulador/omnetpp-6.0.1/bin::/home/simu5g/Simulador/omnetpp-6.0.1/bin:/home/simu5g/Simulador/omnetpp-6.0.1/bin:/usr/bin/gcc:/usr/bin/g++:/home/simu5g/.local/bin:/home/simu5g/Simulador/Setup/Simu5G/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
LD_LIBRARY_PATH=/home/simu5g/Simulador/omnetpp-6.0.1/lib::/home/simu5g/Simulador/Setup/Simu5G/src:/home/simu5g/Simulador/Setup/inet4.4/src:/home/simu5g/Simulador/Setup/veins_inet/src:/home/simu5g/Simulador/Setup/veins-veins-5.2/src:
OMNETPP_RELEASE=omnetpp-6.0.1
OMNETPP_IMAGE_PATH=/home/simu5g/Simulador/omnetpp-6.0.1/images

**Comment by giovanninardini** [comment]
Is this a deterministic error (i.e., it always happens at the same event)? Or does it happen at different times when you run the emulation multiple times?

**Comment by hcr-git** [comment]
Hello, 

thank you for you reply.

It is happening at the same time, at event #18, in the last simulations.

However, I cannot be absolutely sure about this determinism because when we first adapted the extUeAppMecApp emulation, there were emulations that ran successfully (without communication between external apps). 

We will review the settings again.

Thank you,
Helena Rodrigues

**Comment by giovanninardini** [comment]
Usually that kind of error occurs because of some misconfiguration of some mrt file, especially the “gateway” field. For example, when the gateway of one entry is not set, then an ARP request is triggered, and this looks like what is happening in your case.

hope this helps.

Best regards.
Giovanni
