### ISSUE TITLE
MEC App using MEC services

### ISSUE THREAD

**Issue by EstefaniaCC** [Unipisa/Simu5G#159]
Hi all, 

Is there an example of MEC app retrieving information from a MEC service?

Thank you. 

Estefanía.

**Comment by EstefaniaCC** [comment]
Hi Giovanni, 

thanks for your fast response. 
I believe the logging is performed through the MECWarningAlertApp, but does not relate the UE app right?
I understand the logging is performed directly to a file. could you give some hints on how simu5g enables this, since the parameter does not exist directly as configuration option in the .ini files.

thanks. 

Best regards,
Estefanía.

**Comment by giovanninardini** [comment]
Hi,

in that example the MecWarningAlertApp uses the Location Service according to the subscribe-notify paradigm.
This means that the MecApp _subscribes_ to a specific event - in this case, getting in/out of the "warning area". In turn, the Location Service _notifies_ the MecApp only when that event occurs. That is why the information is not periodic.

Best regards.
Giovanni

**Comment by giovanninardini** [comment]
Hello,

I am sorry for the delay.
I have just uploaded a new simulation example with a MEC app querying the RNI Service. You can find it in folder [simulations/NR/mec/rnisTest](https://github.com/Unipisa/Simu5G/tree/2cabeb53fe86222a3d84ee7ffa74d1ccc8fcfc6c/simulations/NR/mec/rnisTest).

Hope this helps.
Giovanni
