### ISSUE TITLE
positioning

### ISSUE THREAD

**Issue by mbalalzade** [Unipisa/Simu5G#163]
hello. I want to know is there any simulation in sium5G that i can put for example 5 UE and 3 GNB in an invironment and then i can measure the RSS that received from users (uplink) in GNB?

**Comment by giovanninardini** [comment]
Hello, 

you can of course set the position of UEs and gNBs as you wish through the INI file.
Some metrics related to signal strength/quality you may observe are the _measuredSinrDl_ (for DL transmissions) or _measuredSinrUl_ (for UL transmissions).
