### ISSUE TITLE
upf_mec module inside mecHost is transmitting packets slowly 

### ISSUE THREAD

**Issue by zazim13** [Unipisa/Simu5G#165]
Hi, 
I am trying to evaluate the performance of a Mec application that I have implemented. My UE is continuously sending packets with a high rate. The problem is that the MecApp is receiving just a few packets. After following packet flow, It seems that the upf_mec module inside the mecHost is transmiting data really slowly(other modules before are transmiting almost all received packets).  I am trying to reduce my delay, is it possible to make the upf_mec module faster, at least as faster as others UPFs ?  
Here some results (input and ouput queues) showing my observations: 
upf_mec incomming packets (If I understand well the queued packet at input queue ->blue and queued packets at output queue ->orange): 
![Screenshot from 2023-07-06 11-01-15](https://github.com/Unipisa/Simu5G/assets/60358257/08044385-3053-4b1c-9e31-acedd2fc608d)
upf_mec outgoing packets(If I understand well the dequeued packet at output queue->orange and dequeued packets at input queue->bleu ): 
![Screenshot from 2023-07-06 11-01-33](https://github.com/Unipisa/Simu5G/assets/60358257/2944bcb4-a362-46a6-bd4c-0add92bff3e8)
We can observe that by the end of my experience less than half of packets received by the upf_mec are transmitted to the next module. 
 
Here the virtualised infrastructure incoming packets 
![Screenshot from 2023-07-06 11-01-54](https://github.com/Unipisa/Simu5G/assets/60358257/5f44dea6-3dd3-46e3-9a6c-1d687a35ba7d)

I precise that I am not sure that the problem comes from the upf_mec only. I just followed the packet flow and upf_mec module is sending less packets that it is receiving .

Sincerly 
Hakim.

**Comment by giovanninardini** [comment]
Hello,

I think you are misinterpreting the charts.

_pppIf_ is the network interface that connects the _upf_mec_ with the _virtualizationInfrastructure_.
_ppp0_ is the network interface that connects the _upf_mec_ with the _iUpf_ (e.g., the 5G core network).

The first chart you posted (incoming packets) refers to the packets that a network interface receive from the IP layer of the same module.
The second chart (outgoing packets) refers to packets that a network interface has sent out. 
Unless the interface drops some packets, it is expectable that they are the same value (as it is in your example).

So, putting the above info together, we have that in the first two charts:
- blue represents the packets that go from the _upf_mec_ to the _virtualizationInfrastructure_ (probably, packets going from the UE to the MEC app)
- orange represents the packets that go from the _upf_mec_ to the _iUpf_ (probably, packets going from the MEC app to the UE)


Likewise, the third chart shows the packets that the network interface of the _virtualizationInfrastructure_ received from its IP layer, hence packets that have been sent out by the _virtualizationInfrastructure_ towards the _upf_mec_ (probably, packets going from the MEC app to the UE) —> and this demonstrate that the _upf_mec_ and _virtualizationInfrastructure_ are working as they should.

**Comment by zazim13** [comment]
Hi, 
Thank you for your answer. Turns out my packets are dropped when the snr is too low 
Hakim.
