### ISSUE TITLE
changing Parameters during Runtime

### ISSUE THREAD

**Issue by Ali-K-Abbas** [Unipisa/Simu5G#168]
hello Dears,

I am trying to make a MEC APP that changes a parameter value during runtime after certain event using the `cPar& param= ue->par("parameter name"); param.setDoubleValue(1); ` , and I was able to see the value change, (also edit the Type in .NED to be @mutable). 
However it didn't take effect when the value of the parameter got called during runtime ,
I've tried tweaking the code in order to recall the value with No success (even recalling the initialize function at some point)  I was working with eNodeB Parameters in MAC layer mostly,
also the use of `handleParameterChange(const char *name)` was not of help to me (I am not sure I am using it right though),
so I just want to make sure that is it me or the change of a parameter value during run time is not applicable ?
PS: Paden me as I am New to the OMNET++ world !

**Comment by linofex** [comment]
Hi, 
this question is not about Simu5G specifically, so I can only suggest you to read the manual:
mutable parameter [section](https://doc.omnetpp.org/omnetpp/manual/#sec:ned-lang:mutable) and handleParameterChange [section](https://doc.omnetpp.org/omnetpp/manual/#sec:simple-modules:handleparameterchange)

best regards
Alessandro
