### ISSUE TITLE
Integration of Veins into Simu5G fails

### ISSUE THREAD

**Issue by mahbub-iut** [Unipisa/Simu5G#17]
Hi,
I have successfully built Simu5G with INET and ran the demo scenario and it ran perfectly fine. However, when I tried to integrate veins for Simulating 5G-enabled vehicular networks using this  [link](http://www.simu5g.org/veins_integration.html) Simu5G failed to build with the error shown in the attachment. I'm not sure how to resolve this issue ..Any insight on this would be really helpful for me. Thanks
![Screenshot from 2021-12-14 13-47-46](https://user-images.githubusercontent.com/20723124/146060824-6dccc006-725d-42c7-85c8-2ee9b16d8a16.png)
.

**Comment by giovanninardini** [comment]
Hello,

it looks like veins was not correctly compiled, or it was not in the correct directory.
Please make sure you put the Veins directory in the correct folder (next to Simu5G and inet4 directories) and you followed all the steps to import Veins and Veins_inet to the IDE correctly.
In the end, you should have a workspace like the one in the left part of the figure below, and Simu5G project references configured as shown in the window.
![Screenshot 2021-12-24 at 09 46 40](https://user-images.githubusercontent.com/7429655/147336448-6f633ed1-b1d0-47ac-8ac9-9c435a4c4675.png)

**Comment by mahbub-iut** [comment]
Thanks ... I had to copy Veins projects into workspace while importing Veins_inet and veins into the project and it worked after that
