### ISSUE TITLE
Bug: Processing of data packet when D2D-UE is not associated to any eNB/gNB

### ISSUE THREAD

**Issue by stefanSchuhbaeck** [Unipisa/Simu5G#175]
This can happen when handovers are active and a UE leaves a eNB but cannot attach to a new one. In this
case the UE is `associated` with a dummy master_Id of zero which does not have any data, leading to nullpointers
in the mac layer processing

See #174

**Comment by giovanninardini** [comment]
#174 has been merged. Thanks.
