### ISSUE TITLE
Error importing Simu5G on VM

### ISSUE THREAD

**Issue by Akareps** [Unipisa/Simu5G#185]
When I attempt to import Simu5G-1_2_1-PnP.ova in Virtualbox, I get the following error:

`E_INVALIDARG (0x80070057)`

Has anyone encountered anything similar? Are there any known fixes? I am using windows 10.

**Comment by giovanninardini** [comment]
Did you make sure that you completed the download of the _whole_ ova file? It should be around 5-6 GB.

**Comment by Akareps** [comment]
Apparently that was the issue. For some reason only about 1gb had been downloaded but the file showed up normally. I redownloaded the file and now it works fine.
