### ISSUE TITLE
Parallel simulation

### ISSUE THREAD

**Issue by WilliamNapolitano** [Unipisa/Simu5G#186]
I'm trying to run a simulation in parallel using the Simu5G framework. Does anyone know of a script that can guide me on how to do this and what parameters need to be set?

**Comment by giovanninardini** [comment]
Hello,

if you mean running one simulation using multiple CPU cores, that is not possible. 

If you mean running multiple simulation instances, each of them using a different CPU, you can take a look at the `opp_runall` command provided by OMNeT++: [https://doc.omnetpp.org/omnetpp/manual/#sec:run-sim:batches-using-opp-runall](https://doc.omnetpp.org/omnetpp/manual/#sec:run-sim:batches-using-opp-runall )
