### ISSUE TITLE
New connection through simulator

### ISSUE THREAD

**Issue by Vickpire** [Unipisa/Simu5G#19]
Hello, 

First of all, I would like to say how great this simulator is and a great possibility to experiment and research!

I am writing to you, not to report a bug, but rather ask if you think it would be possible to create a connection to a locally hosted Node-RED instance using your simulator. If you could provide me some directions for the connection as well, I would really appreciate that. 

Thank you very much in advance. 

Best regards,
Victoria

**Comment by giovanninardini** [comment]
Hi,

thank you for your appreciation of our work!

I have never worked with Node-RED so I am not familiar with it. However, I can say that if you use Simu5G in real-time emulation mode, you can exchange IP datagrams (carrying UDP or TCP data) with applications outside the simulator. Such applications can be located in either the local host or a remote host.

I suggest you to take a look at [this page](http://simu5g.org/emulation.html) ("Running an emulation example with Simu5G" section) of our website to learn how to run an emulation. You can start from the provided examples to build your own testbed.

For more information about real-time emulation with Simu5G, you can read [this paper].(https://ieeexplore.ieee.org/document/9591605).

Hope this answers your question.

Best regards.
Giovanni
