### ISSUE TITLE
Erreur on simu5g omnet++ (makefile)

### ISSUE THREAD

**Issue by Y-AMDIAZ** [Unipisa/Simu5G#193]
Hi , I have an erreur when I download simu5G I dont know how I can do it should I download the lastest version or what ? 
windows11
omnet++ 5.7
inet 4.5.2
Simu5G 1.1.0
<img width="866" alt="Capture d'écran 2024-02-20 104105" src="https://github.com/Unipisa/Simu5G/assets/129278941/249cfd74-5922-4c5c-af07-b4f503d0184b">

**Comment by yqys1226** [comment]
SIMU5G request omnet version at least 6.0.2.

**Comment by giovanninardini** [comment]
> SIMU5G request omnet version at least 6.0.2.

OMNeT++ 6.0 and 6.0.1 are supported as well.
But for sure version 5.7 is not.
