### ISSUE TITLE
Error while running Mec Warning Alert App simulation

### ISSUE THREAD

**Issue by krzycho2** [Unipisa/Simu5G#2]
Hello, 
In simu5g/simulations/NR/mec_warning_alert directory I found a simulation of MEC app. When I run it in fast mode, I get an error:
_"Implicit chunk serialization is disabled to prevent unpredictable performance degradation (you may consider changing the Chunk::enableImplicitChunkSerialization flag or passing the PF_ALLOW_SERIALIZATION flag to peek) -- in module (UEWarningAlertApp) MecSingleCell.car[0].app[0] (id=119), at t=0.014s, event #37"_
Probably that error is caused by INET. 
Could you help me solve it?
I have OMNET++ 5.6.2 and INET 4.2.2 installed as required in http://simu5g.org/install.html

**Comment by krzycho2** [comment]
It happens also onSimu5g-Cars-Pnp virtual machine.

**Comment by giovanninardini** [comment]
Thank you for reporting the issue. This have been fixed in the master branch.
