### ISSUE TITLE
UmRxEntity::reassemble(): failed reassembly runtime Error. Due to wrong SDU  reassemble in multi eNB cases (rare event)

### ISSUE THREAD

**Issue by stefanSchuhbaeck** [Unipisa/Simu5G#20]
Hi, 

I found  a very  rare condition that will lead to a wrongful  reassemble of RLC SDU's in unacknowledged mode (UM)
Setup:

* Multi eNB (in my case 5)
* D2D SideLink multicast communication with eNB support.
* 100 moving  nodes
* 2 Applications with different sized payloads and packet creation intervals. 
* The error occurs after multiple hours into the simulation.

Assume Node A and Node B are connected to eNB1. Node A is on the edge of the reception distance of eNB1 and will  'ping pong' between eNB1 and eNB2 multiple times during the simulation. Each time the connection to the current eNB is lost all UmTxEntities are deleted and recreated if the connection is reestablished . 

Assume now that Node A  just reconnected with eNB1 (see figure bellow). It then creates SDU-1 , SDU-2 and SDU-3. After receiving a grant the mac layer creates the respective PDU's and splits the SDU as shown in the figure. Assume further that Node B, which is also connected to eNB1 and in Sidelink range to Node A, receives PDU21 to PDU24 as shown in  the figure. Node B thus reassembles the SDU's in the UmRxEntity and buffers the first part SDU-3 and waits for the rest of SDU-3.

PDU-26 however is lost due to bad reception quality. NodeA then detaches from eNB1 and connects to eNB2 for a couple of seconds 
only to handover back to eNB1. This will recreate UmTxEntity  which will reste the SDU sequence number count. Node A then 
resumes to send data from the upper layers using the now reset  SDU sequence numbers. Note that the mac layer PDU sequence numbers are not reset by the handover. 

In my simulation it than happened that all PDU's belonging to SDU0 to SDU2 where lost as well as the first part of the 'new' SDU3. The first middle part of the 'new' SDU-3 was received by Node B. In the UmRXEntity the reassemble access only the SDU sequence number which in this case matches the buffered packet, thus reassembling to packets that do not belong together. After the 
last fragment was received the  sanity check in UmRxEntity compares the size with the packet pointer an will  throw an exception. 

This error only occurs if all PDU's between the first fragment of the precious SDU sequence number cycle and the new on are lost. 
If any of these PDU's would reach Node 2 the reassembly would fail and the buffered packet would be dropped as expected. 

One solution is to compare the PDU sequence numbers instead of the SDU sequence numbers. This is possible because  in the UM mode there is no reordering of RLC PDU's. Furthermore the SDU sequence number is only present at the first fragment of the SDU. Mid or end fragments of the SDU do not contain the SDU sequence number information. This information is only  accessible in the simulation.  If introduced the additional check in PR #21 to fix this edge case.

![rlcError](https://user-images.githubusercontent.com/11520228/150544399-c3029cd6-32b7-4237-b6dc-9c82f21f00f3.png)

**Comment by giovanninardini** [comment]
Hi Stefan, 

thanks a lot for finding out this problem and providing a fix! I merged it into the master branch.

Best regards.
Giovanni
