### ISSUE TITLE
VoIP Received Throughput becomes lower with each new UE

### ISSUE THREAD

**Issue by ChristophPargfrieder** [Unipisa/Simu5G#237]
Hey,

I have an issue with a simulation where UEs are created according to their corresponding vehicle in SUMO (co-simulation setup using Veins): These are created according to flows (in total 100 vehicles are created over some defined time). Consequently, most of the UEs are created not at simulation start, but during the simulation. My setup involves a server, router, the UPF and 15 gNBs forming micro cells (carrier frequency is 3.5 GHz) and I use VoIP as app. When evaluating the results, I noticed that the first UEs have some voIPReceivedThroughput:mean larger than 1.3 kbps, but the throughput on application-level quickly gets lower for UEs that are created later on. The app configuration is as follows:

### Server configuration
*.server.numApps = 100
*.server.app[*].typename = "VoIPSender"
*.server.app[*].localPort = 3000 + ancestorIndex(0)
*.server.app[*].destAddress = "UE[" + string(ancestorIndex(0)) + "]"
*.server.app[*].startTime = 1s
*.server.app[*].stopTime = 2500s

### Client configuration
*.UE[*].numApps = 1
*.UE[*].app[0].typename = "VoIPReceiver"

Can someone identify any issue with my configuration? What could be the cause of the decreasing throughput over simulation time?

**Comment by giovanninardini** [comment]
Hard to say... 
It might be that all UEs are being attached by the same gNB? And maybe that gNB has not enough resources to serve all the UEs? 
You should verify which gNB the vehicles connect to once they are created (e.g., using the servingCell metric), and if they perform handover.

**Comment by ChristophPargfrieder** [comment]
> Hard to say... It might be that all UEs are being attached by the same gNB? And maybe that gNB has not enough resources to serve all the UEs? You should verify which gNB the vehicles connect to once they are created (e.g., using the servingCell metric), and if they perform handover.

Thanks for your reply. I already found the reason why the mean throughput becomes lower for UEs that are created at some later point. The issue is the interval that is used to compute the mean throughput is the same for every UE:

double interval = SIMTIME_DBL(simTime() - warmUpPer_);

This works in scenarios where all the UEs are created at simulation begin. However, in the case of UEs that are created during the simulation, the creation time of the UE module should be subtracted here (they did exist before, so considering the entire simulation time for computing the mean is not correct in my opinion).
