### ISSUE TITLE
Problem with module example called standalone

### ISSUE THREAD

**Issue by danielScLima** [Unipisa/Simu5G#242]
Hello everyone.
I have just downloaded and installed the Omnetpp, inet and Simu5G.

Versions:
INET Framework 4: 4.5.4
Simu5G: 1.2.2
Omnet++: 6.1 

I tried to execute the sample called "standalone", but an error appears:

<!> The @enum property is only allowed on string parameters, at C:/Users/Daniel/omnetpp-6.1.0-windows-x86_64/omnetpp-6.1/samples/myomnet/simu5g/src/stack/pdcp_rrc/LtePdcpRrc.ned:39 -- in module (NRPdcpRrcEnb) SingleCell_Standalone.gnb.cellularNic.pdcpRrc (id=236), during network setup

Can someone explain how to fix the error?

![image](https://github.com/user-attachments/assets/1fe9a72f-b5b4-4d2d-8cec-bdaaf82d7ad5)

![image](https://github.com/user-attachments/assets/d98e102f-08ef-4696-81fe-08b2625852cf)

**Comment by giovanninardini** [comment]
Hello,

Simu5G 1.2.2 is not compatible with OMNeT++ 6.1, please use OMNeT 6.0.x until a fix for Simu5G is released.

Best regards.

**Comment by danielScLima** [comment]
Hello @giovanninardini . Thanks for you help.

I followed your indication and installed:

Omnet: Version: 6.0.3
Inet 4: 4.5.4
Simu5G: 1.2.2

By this way, the example runned well.
