### ISSUE TITLE
The principle of integrating with veins?

### ISSUE THREAD

**Issue by daohu527** [Unipisa/Simu5G#25]
I know Simu5G and veins both base on OMNeT++, and I noticed that Simu5G  `Support for vehicular mobility (integration with Veins 5.1)`. So the question is how Simu5G integration with Veins.

Are veins imported as a module? Be able to introduce the interaction method and data flow of the following two? I'm new to Simu5G and look forward to your reply : )

**Comment by daohu527** [comment]
Can VeinsInetMobility be considered as a tool for communicating with sumo, can other network topo be implemented in sim5g?

I mean v2x related simulations like base station occluded by buildings or something. If you have some experience, can you share some?

**Comment by giovanninardini** [comment]
Whatever network topology you configure with SUMO can be simulated within Simu5G.

If your second question is whether the radio signal from the base station can be affected by the environment (e.g. buildings), the answer is that you cannot model buildings and object directly, but the channel model used by Simu5G (which is taken from 3GPP specifications) actually considers (statistically) the presence of objects in the environment when computing the SINR.

**Comment by daohu527** [comment]
Thanks for your kind reply! I read the paper and source code, and I am going to build the environment, I am going to do some V2X simulations : )
