### ISSUE TITLE
Build error while building Simu5G

### ISSUE THREAD

**Issue by mubashirma** [Unipisa/Simu5G#27]
I am using Omnetppv6.0pre11, Inet 4.3.2, Veins 5.1, Simu5G 1.2.0 in Ubuntu 20. I followed the installation guide as the website. Veins, Simu5G, Inet are in the same folder and reference and features boxes are checked.
I am facing the same error all the time. The error is on the attached screenshot.

![Screenshot from 2022-02-16 03-08-07](https://user-images.githubusercontent.com/73335683/154222563-8773fdcf-4fce-44c5-912f-eac69ca42c2b.png)
![Screenshot from 2022-02-16 04-20-26](https://user-images.githubusercontent.com/73335683/154233907-dc1bb6e3-ce68-45f1-97d8-6c54a7d7ae89.png)

**Comment by giovanninardini** [comment]
It looks like that INET was not succesfully compiled. 
Before compiling Simu5G, please make sure you correctly compiled both INET and Veins.

**Comment by mubashirma** [comment]
I complied both Inet and Veins. I run examples from Inet and Veins. It comes to error when Simu5G is complied after Veins.

**Comment by giovanninardini** [comment]
What kind of error? Is that different from the one above?
