### ISSUE TITLE
Spectrum bandwidth used in simu5G

### ISSUE THREAD

**Issue by lexsawada11** [Unipisa/Simu5G#29]
Hi developers,

Thanks for addressing my previous question.  Can you help enlighten me on the spectrum bandwidth used for each of the carrier frequency in `.carrierAggregation.componentCarrier[*].carrierFrequency`  that are being set? Is there any way for me to change the spectrum bandwidth?

Thank for your advise.

**Comment by giovanninardini** [comment]
Hello,

you can use the `*.carrierAggregation.componentCarrier[*].numBands` parameter to change the spectrum bandwidth.
The parameter sets the number of available Resource Blocks in the given component carrier. For example, numBands=25 means 5 MHz, 50 means 10 MHz, 100 means 20 MHz, and so on.

Best regards.
Giovanni

**Comment by nswdxfm20008** [comment]
> Hello,
> 
> you can use the `*.carrierAggregation.componentCarrier[*].numBands` parameter to change the spectrum bandwidth. The parameter sets the number of available Resource Blocks in the given component carrier. For example, numBands=25 means 5 MHz, 50 means 10 MHz, 100 means 20 MHz, and so on.
> 
> Best regards. Giovanni

hi giovanninardini
Besides the way of changing  `*.carrierAggregation.componentCarrier[*].numBands` to adjust the bandwidth, has any other methods to change the bandwidths ?  in my simulation there's just one cell to observe performance under different bandwidth, and i do not prefer to deploy CarrierAggregation

thank for you advise

**Comment by giovanninardini** [comment]
Hello,
I am not sure I fully understand your question. If you want to change the bandwidth of your cell, you need to use the `numBands` parameter. The fact that it is a parameter of the `carrierAggregation` module does not mean that you are deploying carrier aggregation.
In fact, if you set just the parameter `numComponentCarrier = 1`  in the `carrierAggregation` module, then you are actually simulating a scenario without carrier aggregation.

Hope this answers your question.
