### ISSUE TITLE
Error when run simulation

### ISSUE THREAD

**Issue by ericliujian** [Unipisa/Simu5G#3]
When I try to run simulation->NR->cars, I found attached error, could you please tell me how to solve it?
![Screenshot from 2021-06-29 00-44-56](https://user-images.githubusercontent.com/25019274/123738710-4f683480-d873-11eb-9964-d6ca30be09e0.png)

**Comment by mahbub-iut** [comment]
I am having the same issue while running the simulation for the first time... Please keep us updated on your progress ...I will do so if I get to resolve the issue

**Comment by giovanninardini** [comment]
This is something related to your OMNeT++ installation, not to Simu5G. In particular, it seems like you have not installed the _osgEarth_ library correctly.  Please take a look at the OMNeT++ install guide.
