### ISSUE TITLE
Bridge between gNodeB and UE

### ISSUE THREAD

**Issue by ArndtTU** [Unipisa/Simu5G#32]
Ciao professore,

thank you for the simulator.
I am currently working on a project and am hoping for some hints.
I need to create a new type of node that extends the range of a Simu5G base-station. I guess a relay like functionality would be easiest to implement, but deem resource allocation by the gNodeB or the CQI problematic for example. At the moment I am trying to figure out, which parts of the code need to be adapted.

Any kind of hints or help is welcome.
Grazie in anticipo per il vostro supporto!

**Comment by giovanninardini** [comment]
Hello,
if I understand correctly, you would need a module that receives PHY-layer packets and relays them to UEs attached to it (that is, a layer-1 repeater). Is my guess correct?

**Comment by ArndtTU** [comment]
That was the initial plan, yes.
But at the moment I am trying to have a new nodeType that implements both the cellularNic of a gNodeB and of a NRUe. Forwarding is supposed to then take place above the MAC layer.

**Comment by giovanninardini** [comment]
Ok, I see.
I believe it may be possible to implement a brand new node with two NICs, one like the _NrNicEnb_ and one like the _NrNicUe_ (with just one network layer on top of both of them).
However, off the top of my head I do not know if there may be some conflicts between the two NICs, or any other compatibility issue with other nodes in the network.
