### ISSUE TITLE
Make error in Simu5G Build

### ISSUE THREAD

**Issue by kattungakrish** [Unipisa/Simu5G#34]
Hi, I've been trying to build simu5G over the OMNeT++ and INET Framework. I was able to successfully install those two but I'm having issues when I try to build Simu5G over them and I don't understand why those errors occur.  Posting a screenshot here, please guide me with this. 
<img width="1209" alt="Screenshot 2022-03-24 at 3 16 13 AM" src="https://user-images.githubusercontent.com/89295031/159894579-c1c118f2-08cf-416e-94e9-3fe1c7bdca4e.png">

There were about a lot of errors of the same nature. I'm doing this on a MAC OS 12.3 Intel Silicon Chip. I have also tried on windows 11 earlier, and was stuck at the same stage where SImu5G build was failing. Maybe not the same error though.

**Comment by kattungakrish** [comment]
<img width="827" alt="Screenshot 2022-03-24 at 4 07 11 PM" src="https://user-images.githubusercontent.com/89295031/160024451-fee0207c-12c1-4599-a964-8e88a174bb67.png">

A slightly clearer view of the errors from the OMNeT IDE

**Comment by kattungakrish** [comment]
<img width="805" alt="Screenshot 2022-03-24 at 4 09 53 PM" src="https://user-images.githubusercontent.com/89295031/160024615-5711f3b8-8adf-453a-b0fe-17ebf5563f3d.png">

These were some warnings I received while building INET

**Comment by giovanninardini** [comment]
Hello,

what version of OMNeT++ and INET are you using?

**Comment by kattungakrish** [comment]
> Hello,
> 
> what version of OMNeT++ and INET are you using?

I'm using OMNet++ 6.0 pre 11. For INET when I ran OMNeT++ IDE for the first time, I asked me for allowing for an INET framework installation automatically, following which it built a inet 4.3 folder in my designated workspace. I had also tried directly downloading the installation for INET v 4.3.2 as suggested on Simu5G's website and building it from command line or IDE didn't seem to work.

**Comment by kattungakrish** [comment]
<img width="990" alt="Screenshot 2022-03-25 at 12 17 49 PM" src="https://user-images.githubusercontent.com/89295031/160187204-ca80eb5b-e9f9-473b-9763-5e8d902ba3a3.png">

This is what happened when I tried INET installation using terminal on MAC following the install guide given in the inet4.3.2 source code files. There were other multiple warnings with this as well, such as:

<img width="990" alt="Screenshot 2022-03-25 at 12 19 05 PM" src="https://user-images.githubusercontent.com/89295031/160187339-6267e723-b036-4868-a4e0-ee42236bbfe2.png">

**Comment by kattungakrish** [comment]
> Hello,
> 
> what version of OMNeT++ and INET are you using?

Hi any updates on this?

**Comment by giovanninardini** [comment]
> The master branch of the repository has just been updated to make Simu5G work with OMNeT++ 6.0 and INET 4.3.9

Update: the master branch of the repository has just been updated to make Simu5G work with OMNeT++ 6.0 and INET 4.4.0
