### ISSUE TITLE
MEC latency benchmark

### ISSUE THREAD

**Issue by daohu527** [Unipisa/Simu5G#36]
Hi thanks for your good work. I recently tested 2 examples under simu5g, but I am not sure about the latency of 5G MEC is correct.

## Test
I tested in the following two cases
```
simulations\NR\mec\multiMecHost
simulations\NR\mec\singleMecHost
```
and the 5G MEC latency is
![Snipaste_2022-03-29_09-13-37](https://user-images.githubusercontent.com/10419854/160512763-50302333-ef33-416f-9ec5-8df9c5f4ebe8.png)

In average, the upstream delay is **10ms**, while the downstream is **5ms**

## Question
So my questions are
1. Why are the delays different for upstream and downstream?
2. Packet size doesn't seem to have a significant effect on latency, is this normal?
3. When I adjust the message frequency, the MEC MAC layer will report an error, why is this happening?

Any suggestions would be greatly appreciated!

**Comment by linofex** [comment]
Hi,

I am going to respond to your questions:

1. What metrics are you observing for the latency? Latency in the uplink may be higher than the downlink because the UE has to request a scheduling grant from the gNB. This is not necessary in the downlink, so that explains the different latencies.

2. As I can see from your figure, the sizes are 20B and 300B. In 5G networks, in optimal radio channel conditions, such sizes can be easily packed in a single transmission,i.e. Transport Block (TB). So it is normal

3. What error do you get? Can you explain better? 

Best regards, 
Alessandro

**Comment by daohu527** [comment]
Thank you for your reply, Next I want to discuss some details

## Q1
> What metrics are you observing for the latency? Latency in the uplink may be higher than the downlink because the UE has to request a scheduling grant from the gNB. This is not necessary in the downlink, so that explains the different latencies.

I add the timestamp in the message and then use `curtime - receive_msg->time`
```c++
// client side
void UEWarningAlertApp::sendMessageToMECApp(){
  alert->setPayloadTimestamp(inet::simTime());

// server side
void MECWarningAlertApp::handleUeMessage(omnetpp::cMessage *msg) {
  inet::simtime_t delay = inet::simTime() - warnPk->getPayloadTimestamp();
```
Can I optimize this part of the latency because I want to reduce the latency of `client->server->clinet`

## Q2 & Q3
Because I want to adjust the frequency of the messages, I added a new message and sent it directly to MEChost via socket, but I got the following error, I tried 3 times and I got 3 prints

```
<!> NRPacketFlowManagerGnb::ulMacPduArrived - grant [167] for nodeId [2051] not present -- in module (NRMacGnb) singleMecHost.gNodeB1.cellularNic.mac (id=85), at t=26.017s, event #236668
<!> NRPacketFlowManagerGnb::ulMacPduArrived - grant [39] for nodeId [2049] not present -- in module (NRMacGnb) singleMecHost.gNodeB1.cellularNic.mac (id=85), at t=3.039s, event #29598
<!> NRPacketFlowManagerGnb::ulMacPduArrived - grant [39] for nodeId [2049] not present -- in module (NRMacGnb) singleMecHost.gNodeB1.cellularNic.mac (id=85), at t=3.039s, event #29598
```
below is the code

```c++

void UEWarningAlertApp::handleMessage(cMessage *msg)
{
    EV << "UEWarningAlertApp::handleMessage" << endl;
    // Sender Side
    if (msg->isSelfMessage())
    {
        if(!strcmp(msg->getName(), "selfStart"))   sendStartMEWarningAlertApp();

        else if(!strcmp(msg->getName(), "selfStop"))    sendStopMEWarningAlertApp();

        else if (!strcmp(msg->getName(), "selfMecAppTest")) sendTestMessageToMECApp();   \\ I added

void UEWarningAlertApp::sendTestMessageToMECApp(){
    inet::Packet* pkt = new inet::Packet("WarningTestPacket");
    auto test = inet::makeShared<WarningTestPacket>();
    test->setPayloadTimestamp(inet::simTime());
    test->setType(TEST_WARNING);

    test->setChunkLength(inet::B(300));
    pkt->insertAtBack(test);

    socket.sendTo(pkt, mecAppAddress_ , mecAppPort_);
    EV << "UEWarningAlertApp::sendTestMessageToMECApp() - start Message sent to the MEC app" << endl;

    scheduleAt(simTime() + 1, selfMecAppTest_);
}
```

**Comment by daohu527** [comment]
@linofex any updates, I am very concerned about the delay, because I want to do some V2X related applications

**Comment by linofex** [comment]
#Q1
Try changing the numerology. This will reduce the TTI duration and so some operations both in DL and UL. To do this you have to set numerlogyIndex parameter in the .ini configuration (values between 0 (as now) and 4 (shortest TTI)) [see simulations/NR/test_numerology]

#Q2 Q3
I have to investigate a bit for this error. By the way, the packetFlowManager module is used with the MEC RNI service. If you do not use it, just set the **hasRNISupport** parameter (in the .ini file) to false, this will not load such module.

**Comment by daohu527** [comment]
1. I tested and modified the parameter of NumerologyIndex, the delay is indeed reduced, but when the NumerologyIndex=3 is set, the delay is already lower than 1ms.

2. After closing hasRNISupport, the problem of sending data too fast can indeed be solved, but is this module used for traffic management?

**Comment by linofex** [comment]
Hi,

1. Yes, ss previously said, changing numerology makes it possible to reduce some operations duration and so the e2e latency.

2. Modules for RNI support refer to the RNI MEC service. The latter provides network information like tput, cell usage, and delays to the MEC Apps. So, if your MEC scenario does not make use of the RNI service, you can safely set **hasRNISupport** to **false**, without affecting anything on the underlying simulated 5G network.
