### ISSUE TITLE
eNB and gNB

### ISSUE THREAD

**Issue by wggegshjg** [Unipisa/Simu5G#37]
What is the difference between eNB and gNB? how can i make eNB and gNB use different band in the same network?

**Comment by giovanninardini** [comment]
Hello, 
- eNB is the base station node of a 4G network;
- gNB is the base station node of a 5G network.

You can use both of them in a simulation, just put them in the same NED network file. Then, in the INI file, you can configure them to use different carriers. To do so, configure the _carrierAggregation_ module with two component carriers having different frequencies:

```
*.carrierAggregation.numComponentCarriers = 2
*.carrierAggregation.componentCarrier[0] = 2GHz
*.carrierAggregation.componentCarrier[0] = 4GHz
```

Assuming your eNB and gNB are called _enb_ and _gnb_ respectively, you can configure their channel models to use different component carriers:

```
*.enb.cellularNic.channelModel[0].componentCarrierIndex = 0  # this will use CC 0 (2 GHz)
*.gnb.cellularNic.channelModel[0].componentCarrierIndex = 1  # this will use CC 1 (4 GHz)
```

You can refer to the example simulations/NR/dualConnectivity, which reports a scenario with both a eNB and a gNB in a non standalone 5G configuration.

Best regards.
Giovanni
