### ISSUE TITLE
Building error with SIMU5G

### ISSUE THREAD

**Issue by juansebastiani2cat** [Unipisa/Simu5G#39]
Hello,

I have downloaded and tested Omnet++ 6.0 rc2 and then downloaded and tested INET 4.3 in a Windows 11 machine. I have copied the SIMU5G zip file and extracted right next to INET 4.3 folder. I then imported it using the File -> Import -> Existing project into Worspace method. The issue arises when I try to execute some of the examples as I would need to build the whole project (at least once I think). After a while compiling I get the following errors: 

![image](https://user-images.githubusercontent.com/85935421/162158302-24c9e7a3-07b9-4960-9ea8-f0a03040ff62.png)

The location error in detail is the following: 

Description
`incomplete type 'const Binder' used in type trait expression	Simu5G-1.2.0		line 722, external location: C:\Users\34663\Downloads\omnetpp-6.0rc2\omnetpp-6.0\tools\win32.x86_64\mingw64\include\c++\10.3.0\type_traits	C/C++ Problem`

I would appreciate any advice or answer regarding this issue. Thanks in advance

**Comment by giovanninardini** [comment]
Hello,

current version of Simu5G is not working with OMNeT++ 6.0rc2.
As reported in the [website](http://simu5g.org/install.html) and in the [readme file](https://github.com/Unipisa/Simu5G/blob/master/README.md), version 1.2 of Simu5G requires:
- **OMNeT++ 6.0pre10** or **OMNeT++ 6.0pre11**
- **INET 4.3.2**

We hope to make the simulator compatible with latest version of OMNeT/INET soon.

Best regards.
Giovanni

**Comment by juansebastiani2cat** [comment]
Ok I understand. I downloaded and executed OMNet 6.0 pre 11 and INET 4.3.2. Nonetheless, I still present the following errors while compiling: 

![image](https://user-images.githubusercontent.com/85935421/162204296-d91ccbfe-d252-4e09-a09e-29fb8ad2eb9a.png)

Thanks in advance for your answer.

**Comment by giovanninardini** [comment]
It looks like it cannot find INET's modules. 
Please make sure INET has been imported in the workspace and built correctly.

**Comment by juansebastiani2cat** [comment]
Hello. As the INET's modules are being imported manually (Due to the specific requirement of a singular version), I also downloaded manually the INET libraries and imported them to the workspace in no specific folder. Is there any specific directory where I should put the INET and SIMU5G folders ?

**Comment by giovanninardini** [comment]
Hello,

try the following:
- right click on the Simu5G folder in the left side of the OMNeT++ IDE;
- select _Properties_ -> _Project References_;
- make sure the INET project is ticked, as in the attached figure
 
![image](https://user-images.githubusercontent.com/7429655/162930247-22c42fd1-d97f-4b99-8403-1680e2cc7a53.png)

**Comment by juansebastiani2cat** [comment]
Ok, now it's working. Thanks a lot for your answers.
