### ISSUE TITLE
using Simu5G with OAI-5G core Network and RAN

### ISSUE THREAD

**Issue by mahbub-iut** [Unipisa/Simu5G#4]
We have used OpenAirInterface to create our 5G core Network and 5G-RAN. I was wondering if the packet drops and delay modules 0f Simu-5G can be used together with OAI to simulate packet drops and delays ... Any insight would be really helpful

**Comment by giovanninardini** [comment]
With Simu5G you can simulate the entire 5G network and obtain statistics about packet loss and delay, with no need of using external tools. 
However, it could also be possible to integrate other tools like OAI: for example, you could use the core network provided by OAI together with the RAN provided by Simu5G, possibly using the real-time emulation feature. 
See [here](http://simu5g.org/emulation.html) and the examples [here](https://github.com/Unipisa/Simu5G/tree/master/emulation) for more information about network emulation with Simu5G.

**Comment by mahbub-iut** [comment]
Thanks for the response ... We are trying to use Simu5G emulation feature with our work ...I was wondering if it's possible to use  OAI UE's and Core Network with the eNodeB of Simu5G
