### ISSUE TITLE
getSINR

### ISSUE THREAD

**Issue by wggegshjg** [Unipisa/Simu5G#41]
in LteNic.ned      string LteChannelModelType = default("LteRealisticChannelModel");   
but  in LtePhyUe.cc file:
// get RSSI from the eNB
                std::vector<double>::iterator it;
                double rssi = 0;
                std::vector<double> rssiV = primaryChannelModel_->getSINR(frame, cInfo);
                for (it = rssiV.begin(); it != rssiV.end(); ++it)
                    rssi += *it;
                rssi /= rssiV.size();   // compute the mean over all RBs

std::vector<double> LteChannelModel::getSINR(LteAirFrame *frame, UserControlInfo* lteInfo)
{
   std::vector<double> tmp;
   tmp.push_back(10000);
   return tmp;
}

I want to getSINR  using  LteRealisticChannelModel. what should I do？

**Comment by giovanninardini** [comment]
I am not sure I understand your question.

LteRealisticChannelModel is a class derived from LteChannelModel, and the object _primaryChannelModel_ (whose type is a pointer to LteChannelModel) is instantiated as LteRealisticChannelModel. 

When you invoke 
`std::vector rssiV = primaryChannelModel_->getSINR(frame, cInfo);`
the _getSinr()_ function of class LteRealisticChannelModel is actually called.
