### ISSUE TITLE
RLC AM mode

### ISSUE THREAD

**Issue by Schempp94** [Unipisa/Simu5G#43]
By default the RLC UM mode is used (src/stack/rlc/LteRlc.ned):
string LteRlcUmType = default("LteRlcUm");                   // One of: "LteRlcUm", "LteRlcUmD2D"

However, the AM module (including the AM parameters) is already defined.

It is possible to change the RLC mode to AM? I have been trying to change all the parameters related to this, but I get some errors, perhaps I am forgetting some of them.
I am not sure if it possible to use RLC AM mode (I know that it is still under testing).

Thank you in advance.

**Comment by giovanninardini** [comment]
Hello,

the RLC mode type is controlled by the _LtePdcpRrcBase::setTrafficInformation()_ function, based on the parameters defined in the _LtePdcpRrc.ned_ file and the type of application traffic. Please take a look at that function.

However, AM mode is currently not supported unfortunately.
