### ISSUE TITLE
Different Physical Resource Blocks for different eNB

### ISSUE THREAD

**Issue by juansebastiani2cat** [Unipisa/Simu5G#47]
Dear all,

I'm creating a simulation scenarion where I'd have two eNB: one saturated and the other one with  available resources. My idea is to modify the amount of Physical Resource Blocks (directly modifying the BW that each eNB has), and then assigning less resource blocks to one of the eNB than the other. The issue is that when I try to assign the amount of bands, I cannot differentiate it per each eNB. 

`*.carrierAggregation.componentCarrier[*].numBands`

EDIT: 

Is it possible to add more carrier components and then assign individual PRB to each one? 

```
*.carrierAggregation.numComponentCarriers = 2
*.carrierAggregation.componentCarrier[0].numBands = ${numBands=25}
*.carrierAggregation.componentCarrier[1].numBands = ${numBands=100}

```
and then assign the carrier component individually to each eNB ?
```

*.enb[0].cellularNic.channelModel[0].componentCarrierIndex = 0
*.enb[1].cellularNic.channelModel[0].componentCarrierIndex = 1
```

Is there any other way to change the capacity of the eNBs ? 

Thanks in advance for your answers.

**Comment by giovanninardini** [comment]
Hello,

you can create two component carriers and assign different number of RBs, as long as you also assign different carrier frequencies to them. This means that the two eNBs will not interfere each other.

Alternatively, if you need one eNB with heavy traffic and one eNB with light traffic, you could use background UEs to create some background traffic in the first eNB. This will just occupy RBs without actually simulating the UEs.  
You can find an example of usage of background traffic in folder simulations/NR/bgTraffic (see for example [this line](https://github.com/Unipisa/Simu5G/blob/be531bd0ced6d8ba83255111521fef8d27e03adb/simulations/NR/bgTraffic/omnetpp.ini#L57), [this line](https://github.com/Unipisa/Simu5G/blob/be531bd0ced6d8ba83255111521fef8d27e03adb/simulations/NR/bgTraffic/omnetpp.ini#L108) and [this line](https://github.com/Unipisa/Simu5G/blob/be531bd0ced6d8ba83255111521fef8d27e03adb/simulations/NR/bgTraffic/omnetpp.ini#L165))

**Comment by juansebastiani2cat** [comment]
Got it, thanks a lot for your answer
