### ISSUE TITLE
Vector results of CBR Application contains only one value at each **.app[*]

### ISSUE THREAD

**Issue by suryapusapati** [Unipisa/Simu5G#53]
Dear Authors,

I have tried several times to get vector values by simulating "CbrSender" and "CbrReceiver" at my application layer. I was unable to get continuous values of cbrGeneratedThroughtput:vector and cbrReceivedThroughtput:vector. But cbrFrameDelay:vector has continues values. I am a new user of Simu5G therefore I cannot provide any detailed information.
I have simulated CBR mentioned in:
[dualConnectivity_multicell](https://github.com/Unipisa/Simu5G/blob/master/simulations/NR/dualConnectivity_multicell/omnetpp.ini)
[demo](https://github.com/Unipisa/Simu5G/blob/master/simulations/demo/omnetpp.ini)

Surya

**Comment by giovanninardini** [comment]
Hello,

_cbrGeneratedThroughput_ and _cbrReceivedThroughput_ are not vector metrics.
They are only collected at the end of the simulation and stored as scalar values (see `finish()` function in CbrSender.cc and CbrReceiver.cc).

Best regards.
Giovanni

**Comment by suryapusapati** [comment]
Hello,

I thought it was a vector value of end-to-end throughput. Could I archive that in any of the application models??

Thanks,
Surya

**Comment by giovanninardini** [comment]
You could modify the CbrReceiver.ned file so that the received throughput statistic is recorded:

@statistic[cbrReceivedThroughtput](title="Throughput received at the application level"; unit="Bps"; source="cbrReceivedThroughtputSignal"; record=timeavg,mean,sum, **vector**);

Then, you should also modify the CbrReceiver.cc file, so that the _cbrReceivedThroughput_ metric is emitted every time you receive a packet, e.g., in the _handleMessage()_ function.

**Comment by suryapusapati** [comment]
Thank you for your input.

I found a new issue now. I am having an error "cannot find serializer" when enabling pcapRecoder at the router. If I use some other application type such as UdpBasicApp, VoIPSender, etc. I had no issues. Moreover, I am having this error only while using CbrSender -- CbrReciever as my application.

![Screenshot 2022-06-20 175421](https://user-images.githubusercontent.com/59798127/174690242-f372322f-fd11-4a3d-992c-60c69911c2a7.jpg)
This is a screenshot of the error in the NRcar simulation example provided by Simu5G.

Surya

**Comment by suryapusapati** [comment]
I also found that in `src/apps/cbr` files such as `CbrPacketSerializer.cc` and `CbrPacketSerializer.h` are missing. I suspect these files are related to the following issue.

**Comment by suryapusapati** [comment]
> You could modify the CbrReceiver.ned file so that the received throughput statistic is recorded:
> 
> @statistic[cbrReceivedThroughtput](title="Throughput received at the application level"; unit="Bps"; source="cbrReceivedThroughtputSignal"; record=timeavg,mean,sum, **vector**);
> 
> Then, you should also modify the CbrReceiver.cc file, so that the _cbrReceivedThroughput_ metric is emitted every time you receive a packet, e.g., in the _handleMessage()_ function.

I have added **record** = **vector** at **@statistic[]**.
But can you please provide more information on how to modify the function `CbrReceiver::handleMessage()`? I am a new user of OMNeT++.

**Comment by giovanninardini** [comment]
One option is to modify the code after line 62 (inside the _if_ block) in `CbrReceiver::handleMessage()` function and add the following code:

```
simtime_t elapsedTime = simTime() - getSimulation()->getWarmupPeriod();
emit( cbrReceivedThroughtput_, recvBytes_ / elapsedTime.dbl() );
```

This will add one value to the vector representing the throughput received since the beginning of the simulation.

**Comment by suryapusapati** [comment]
Thanks, I will make the changes.

**Comment by suryapusapati** [comment]
Hello Giovanni,

Thank you for your reply. As the name suggestion i assumed that it records
vector results. So my pull request can be closed.

Thanks,
Surya
