### ISSUE TITLE
have troubles when running runw_Socket.sh

### ISSUE THREAD

**Issue by HaHaWh** [Unipisa/Simu5G#55]
Hi, When I run the runw_Socket.sh, it cannot open Qtenv. I don't know if simu5g starts successfully，
Is this normal?

```
~/omnetpp-6.0pre11-src-linux/omnetpp-6.0pre11/samples/mytest/simu5G/emulation/extclientserver$ sudo ./run_wSocket.sh 
Actual changes:
rx-checksumming: off
tx-checksumming: off
        tx-checksum-ip-generic: off
        tx-checksum-sctp: off
tcp-segmentation-offload: off
        tx-tcp-segmentation: off [requested on]
        tx-tcp-ecn-segmentation: off [requested on]
        tx-tcp-mangleid-segmentation: off [requested on]
        tx-tcp6-segmentation: off [requested on]
```

Thank you in advance.

**Comment by giovanninardini** [comment]
Hello,

when launching the command, you should see something like this:
![image](https://user-images.githubusercontent.com/7429655/173331467-6f5ff79e-7ee4-4fdd-ba52-6aaa10fed052.png)

If not, try to launch the command without "sudo".

Best regards.

**Comment by HaHaWh** [comment]
Thank you for your reply, but I still have some issues. 
when launching the command without "sudo"，I get something similar. But when I run the iperf command, there is still an error and I can't seem to connect to my server. I have deployed according to the official example. 
How can I solve this problem ?




![ZP O2FAP73BJNDQU9T}8@7U](https://user-images.githubusercontent.com/105922598/173582156-5bc8848c-13a4-4d63-b607-de9901f0de55.png)

**Comment by giovanninardini** [comment]
How did you launch the server?

From the README, the correct sequence of operations is:

```
4) Run the external server, e.g. use "Iperf" with the following command:
  	    
  	iperf -s -P 1 -i 1 -p 10021

5) Run the emulation by launching either
     
    ./run_wSocket.sh 
 
6) Run the external client, e.g. use "Iperf" with the following command:
  	    
  	iperf -c 10.0.2.1 -P 1 -i 1 -m -p 10021 -M 536.0B -n 10.0M -f m
```

**Comment by HaHaWh** [comment]
Hello，I'm sure that I Iaunch the server in this order. Beyond that，how can I find the cause of the error?

**Comment by giovanninardini** [comment]
If you launch the exact same configuration as provided with the package, there should be no reason to not working, although  see that the command you issued is a bit different from the one I suggested in the comment above (e.g. you are using iperf3 instead of iperf, you are not indicating the port number, ...)

In addition, you can also try to use Wireshark to see if packets are received at the virtual ethernet interfaces.
