### ISSUE TITLE
Couldn't make simu5G

### ISSUE THREAD

**Issue by SOANykun** [Unipisa/Simu5G#6]
Whenever I make Simu5G, it always report error: unable to load'../out/clang-debug/src/libsimu5g_dbg.dll.a': No such file or directory,my omnetpp version is 6.0pre11 and inet version is 4.3.2.
![image](https://user-images.githubusercontent.com/37335717/131872114-9a58ca68-874d-4647-83d5-7a85177a5b89.png)

**Comment by giovanninardini** [comment]
Try to reinstall OMNeT++ like this:
- move to the omnetpp-6.0pre11 directory;
- open the "configure.user" file
- edit the line PREFER_CLANG = no
- ./configure  
- make

Then, try to build again INET and Simu5G.

**Comment by SOANykun** [comment]
Thank you for your answer, but after trying the method you provided, the same error will still occur.
The OS I use is Windows 10.
![image](https://user-images.githubusercontent.com/37335717/131887234-e7f78631-4830-476d-8fb0-f2223f4b5b4d.png)

**Comment by SOANykun** [comment]
> Try to reinstall OMNeT++ like this:
> 
> * move to the omnetpp-6.0pre11 directory;
> * open the "configure.user" file
> * edit the line PREFER_CLANG = no
> * ./configure
> * make
> 
> Then, try to build again INET and Simu5G.

Hello, first of all, thank you for your answer. I have tried your method many times recently and still report the similar error as before. Is it caused by the operating system?

**Comment by giovanninardini** [comment]
Have you tried making a complete clean of INET and Simu5G projects before recompiling?

For example, typing `make cleanall` from the command line in both INET and Simu5G folders?
Or, if you are in the IDE, right-click on Simu5G project -> Clean project?

**Comment by manishkjain21** [comment]
I had the same issue as mentioned by SOANykun. I am unable to build simu5G and have issues related with libsimu5g_dbg.dll.a being not found. I did the mentioned steps. I am building it on Windows 10.

**Comment by alaasam** [comment]
@manishkjain21  did you solve the problem? I am facing the same issue and I couldn't solve it.

**Comment by manishkjain21** [comment]
Yes I was able to solve the problem by doing the following.
1. Go to properties of Simu5G in omnet++
2. Under the OMNeT++ tab go to "makemake"
3. Click on src:makemake, this should enable the builc Makemake option on the right column. Click on "Options"
4. Inside "Options", click on the custom tab. 
5. Add the following in the end in the section where it mentions the code section to be included in Makefile
`LDFLAGS += -Wl,-Xlink=-force:multiple`

This is how it should look:
```
#
# Use the new message compiler introduced in OMNeT++ 5.3
#
MSGC:=$(MSGC) --msg6

#
# on Windows we have to link with the winsock2 library as it is no longer added
# to the omnetpp system libraries by default (as of OMNeT++ 5.1)
#
ifeq ($(PLATFORM),win32.x86_64)
  LDFLAGS += -lws2_32
endif

LDFLAGS += -Wl,-Xlink=-force:multiple
```
