### ISSUE TITLE
How to optimise simulation run time?

### ISSUE THREAD

**Issue by suryapusapati** [Unipisa/Simu5G#60]
Dear authors,

Could you please suggest a better way to boost the simulation run?

I am simulating a dense urban vehicular network using Simu5G. I would like to simulate for 3600 seconds. But as the simulation runs the Simsec/sec ratio keeps on decreasing. I have enabled parallel build for multiple processor usage, disabled graphical interface, use release mode and run in express mode. But still, I had minimal performance improvements.

Best wishes,
Surya

**Comment by wischhof** [comment]
How many vehicles equipped with a cellular MAC are you simulating? Simu5G - due to calculations that need to be performed per TTI - has a relatively high computational cost per simulated node. For a large (>100) number of vehicles using a cellular interface, the simsec/sec ratio will be low just due to the complexity of the model.

**Comment by suryapusapati** [comment]
Thank you for your comments professor. Yes, I am simulating more than 100 vehicles. With the help of randomTrip.py, I am generating vehicles for 3600sec. I have 8 gNodeB's full inter-connected for the x2 interface, and at the application layer, I am using a bi-directional configuration of the CBR App. To reduce the complexity I reduced the packet size, and it did work.

Please let me know if you have any suggestions on the configuration.

**Comment by suryapusapati** [comment]
Thank you so much @giovanninardini for the information.

I have made changes to fbPeriod and fbDelay but did'nt find significant changes. This might be due to higher complecity of my network.

I have disabled unnecessary statistics recording, so I was able to improve simulation speed. Moreover, it also helped me reduce the file size of output results.
