### ISSUE TITLE
Possibility of Using Simu5G as Real-Time Simulator with an External Tool

### ISSUE THREAD

**Issue by buraksenkus** [Unipisa/Simu5G#64]
Hi,

I want to create a real time emulator/simulator using Simu5G's lower layer models. I will try to explain the model in my mind in detail. I hope it's understandable enough. I would be very grateful if you could tell me if it is possible to do this with Simu5G, and if possible how I can do it.

First of all, I have an emulator which I can create any number of vehicles and base stations with their **mobility patterns**. All of these nodes (vehicles and base stations) **generate V2X messages**. I can run this emulator in real-time and monitor communication between created nodes. Currently, this emulator doesn't use cellular communication and **my main goal is to make this emulator to use cellular communication** as well.

In order to enable vehicles and base stations to communicate with the 5G infrastructure, I came up with a simple method (by the way, I am not very familiar with the theory of C-V2X communication). I can run the same scenario simultaneously in Simu5G and use only MAC, PHY layers and channel modeling capabilities of Simu5G. The mobility information of the nodes and the packet content up to the MAC layer will be transferred to Simu5G **with the help of an API** from my own emulator. In this way, Simu5G will only simulate cellular network communication.

After creating such a system, I'll try to measure basic reliability metrics like packet drop rate, delay etc.

Can I achieve my goal using Simu5G?

Thanks in advance!

**Comment by giovanninardini** [comment]
Hello,

what you can do with Simu5G is to make IP packets getting into a UE (hence, at the IP layer) from the external world (e.g. you emulator). Then, those packets can be re-routed through the cellular NIC provided by Simu5G, which will transmit the packets towards a (simulated) gNB (base station) or another UE through D2D communication. At the UE, for example, packets can be forwarded to the IP layer, and from there they can be sent out to an external application again (e.g. your emulator).
The examples in the "emulation" folder may help you to understand whether you can adapt them to your scenario.

**Comment by buraksenkus** [comment]
Thanks for your explanation. I'll try that approach.

Regards!
