### ISSUE TITLE
set Resource Type for packet forwarding treatment

### ISSUE THREAD

**Issue by gehirndienst** [Unipisa/Simu5G#72]
Hello!

as it is written at the end of README, Simu5G currently (I hope only currently) does not support bearers. It means I can not set resource type for my packets (gbr, dcgbr, ngbr), which is the part of QoS. But at the same time I see some gbr/ngbr getters and setters in StatsCollector classes. Does it mean it is still possible to set RT somehow?

**Comment by giovanninardini** [comment]
Hello,

no, at the moment Simu5G does not support bearers for handling QoS.
The statsCollector class is only used by our MEC model to retrieve information related to the Radio Network Information Service (RNIS). 
According to the ETSI MEC standard, the RNIS API should expose information for all the types of bearers, so we added getters/setters for all of them for better standard compliance, although only the non-gbr ones are actually implemented and returns useful information.
