### ISSUE TITLE
[Question] Direct D2D Communication

### ISSUE THREAD

**Issue by buraksenkus** [Unipisa/Simu5G#74]
Hi,

My question may be silly since the theoretical knowledge about C-V2X is limited, but there is something I'm curious about on Simu5G.

I know that D2D communication is possible in Simu5G but as far as I understand it is not possible without a base station. Can I do it without a base station? I guess PC5 interface provides this feature but Simu5G doesn't have PC5 implementation.

Thanks in advance!

**Comment by wischhof** [comment]
D2D via Sidelink (PC5) is feasible in two different Modes: 

- In network-assisted mode (Mode 3 for Lte, Mode 1 for 5G), the eNodeB/gNodeB assigns the ressources, but the data itself is exchanged directly via sidelink. 
- In un-assisted mode/without base station coverage (Mode 4 for Lte, Mode 2 for 5G), the UEs select (pre-defined)ressources without any assistance of a base station.

Simu5G currently only models network-assisted modes (see [http://docenti.ing.unipi.it/g.nardini/papers/IWSLS2_2016_D2D.pdf](http://docenti.ing.unipi.it/g.nardini/papers/IWSLS2_2016_D2D.pdf)).

If you need to model the other modes, an extension by A. Hegde of THI extends SimuLte with these, see [https://github.com/anupama1990/Artery-C](https://github.com/anupama1990/Artery-C)

**Comment by buraksenkus** [comment]
Hi @wischhof,

Thank you so much for your detailed explanation. Now, I have a clear understanding about situation.
