### ISSUE TITLE
Frame structure

### ISSUE THREAD

**Issue by gustavocainelli** [Unipisa/Simu5G#76]
Dear developers,

Is it possible to configure the frame structure? I know that we can configure the slot structure in UL and DL symbols, but can we for example configure a frame like DDDSU?

Thank you in advance
Gustavo Cainelli

**Comment by giovanninardini** [comment]
Hello,

the current model allows you to decide the slot structure, as you correctly observed - i.e., for each slot, you can decide how many DL/UL symbols it is configured with.
But then each slot will have that same structure. So you cannot have, say, N slots with DL symbols only, followed by M slots with UL symbols only.

**Comment by gustavocainelli** [comment]
Dear Giovani, Do you have an advice (first steps maybe?) if I want to implement such kind of slot format (N slots with DL symbols only, followed by M slots with UL symbols only)?

Thank you very much

**Comment by giovanninardini** [comment]
Hello,

that would be a useful feature to add to the simulator. However, at the moment we do not have the manpower to add it in the very next future, but contributions from the community (if any) are welcome.
