### ISSUE TITLE
problems when run the NR/cars VoIP_DL example

### ISSUE THREAD

**Issue by 613lys** [Unipisa/Simu5G#77]
Hi,

When I run the NR/cars VoIP_DL example, it seems that the packets sent from server doesn't reach the cars.

The log is:

** Event #37952  t=3.416909690161  Highway.router.ipv4.ip (Ipv4, id=102)  on VoIP (inet::Packet, id=15127)
INFO:Received (inet::Packet)VoIP from network.
DETAIL:Received datagram `' with dest=10.0.1.38
INFO:Routing (inet::Packet)VoIP (68 B) [[inet::Ipv4Header, length = 20 B | inet::UdpHeader, port:3000->3000, payloadLength:40 B, length = 8 B | VoipPacket, length = 40 B]] with destination = 10.0.1.38,
WARN:unroutable, sending ICMP_DESTINATION_UNREACHABLE, dropping packet
DETAIL (Icmp)Highway.router.ipv4.icmp:sending ICMP error ICMP-error-#246-type3-code0
INFO (Icmp)Highway.router.ipv4.icmp:Sending (inet::Packet)ICMP-error-#246-type3-code0 (36 B) [[inet::IcmpHeader, length = 8 B | inet::Ipv4Header, length = 20 B | inet::UdpHeader, port:3000->3000, payloadLength:40 B, length = 8 B]] to lower layer.

It seems the packets are dropped at the router. Can I know how can I let the car receive the packets?

**Comment by giovanninardini** [comment]
Hello,

if I run the _NR/cars VoIP_DL_ example I can see that packets are reaching their destination correctly, so everything seems working fine.
