### ISSUE TITLE
Handover process simulation problem

### ISSUE THREAD

**Issue by SOANykun** [Unipisa/Simu5G#79]
Hi, if I want to use Simu5G for cell handover simulation, where can I configure the parameters of handover management? For example, cell parameters such as **handover threshold** and **offset**，etc.

**Comment by giovanninardini** [comment]
I am not sure what you exactly mean by handover threshold and offset.
However, handover parameters can be found in the `LtePhyBase` module. From the NED/INI file, you can enable/disable the handover and configure the `handoverLatency`, i.e. the time needed to complete a handover procedure.
From the C++ code, in `LtePhyUe:initialize()` function, you can check (and modify, if you wish) other parameters such as the hysteresis. Unfortunately, they are not configurable from the NED at the moment.
