### ISSUE TITLE
I can't get the 3 defined signals in the file in the outputs

### ISSUE THREAD

**Issue by edadilann** [Unipisa/Simu5G#8]
Hello there;
I am interpreting various outputs from Simu5G sample simulations. But I can't get the 3 defined signals in the CbrSender.cc file (which is also the Receiver) in the outputs. I will add the signals below.

simsignal_t CbrSender::cbrGeneratedThroughtputSignal_ = registerSignal("cbrGeneratedThroughtputSignal");
simsignal_t CbrSender::cbrGeneratedBytesSignal_ = registerSignal("cbrGeneratedBytesSignal");
simsignal_t CbrSender::cbrSentPktSignal_ = registerSignal("cbrSentPktSignal");

When I ran it by putting a breakpoint, I saw that the following commands did not work.

emit(cbrGeneratedBytesSignal_, size_);

In addition, no command has been written to the "cbrSentPktSignal" signal and I can't get it in the output.

**Comment by giovanninardini** [comment]
Hello,
which simulation example did you run?

**Comment by edadilann** [comment]
Dual Connectivity MultiCell but I used CBR in the application setup.

**Comment by giovanninardini** [comment]
In the latest version of the code, i.e. in the master branch, CBR is used as application for the dualConnectivity_multicell scenario,

https://github.com/Unipisa/Simu5G/blob/master/simulations/NR/dualConnectivity_multicell/omnetpp.ini

By running the examples, the statistics you mention are produced correctly.

**Comment by edadilann** [comment]
Thank you i will check !
