### ISSUE TITLE
bandwidth parameter

### ISSUE THREAD

**Issue by wggegshjg** [Unipisa/Simu5G#81]
dear author
I want to know where to set the subbandwidth parameters of the eNodeB and gNodeB;
I want to set different bandwidth for two types of BS；
for example,
*.carrierAggregation.componentCarrier[0].carrierFrequency=2GHz
*.carrierAggregation.componentCarrier[0].numBands=50
*.carrierAggregation.componentCarrier[1].carrierFrequency=28GHz
*.carrierAggregation.componentCarrier[1].numBands=50
and Each vehicle（0） can obtain 10Mhz bandwidth；
Each vehicle（1） can obtain 100Mhz bandwidth；

**Comment by wggegshjg** [comment]
for example,
*.carrierAggregation.componentCarrier[0].carrierFrequency=2GHz
*.carrierAggregation.componentCarrier[0].numBands=50
and Each vehicle（ue） can obtain 10Mhz bandwidth；

**Comment by wggegshjg** [comment]
when i measurement end-end delay，The delay of using a 4g（only） base station is 15ms；
and The delay of using a 5g（only） base station is 14.5ms ；
In comparison, 5g has no advantage

**Comment by giovanninardini** [comment]
> dear author I want to know where to set the subbandwidth parameters of the eNodeB and gNodeB; I want to set different bandwidth for two types of BS； for example, *.carrierAggregation.componentCarrier[0].carrierFrequency=2GHz *.carrierAggregation.componentCarrier[0].numBands=50 *.carrierAggregation.componentCarrier[1].carrierFrequency=28GHz *.carrierAggregation.componentCarrier[1].numBands=50 and Each vehicle（0） can obtain 10Mhz bandwidth； Each vehicle（1） can obtain 100Mhz bandwidth；

The _numBands_ parameter controls the bandwidth. It is the number of Resource Blocks assigned to that specific carrier. For example, with 4G and 5G with numerology 0, "50 RBs" mean 10MHz bandwidth, "100 RBs" mean 20MHz bandwidth, and so on.

**Comment by wggegshjg** [comment]
> 参数控制带宽。它是分配给该特定运营商的资源块数。例如，对于命理为 0 的 4G 和 5G，“50 RUB”表示 10MHz 带宽，“100 RUB”表示 20MHz 带宽，依此类推。

thanks
This means that the RB of each 4G and 5G BS has the same resource; Each RB occupies 0.2Mhz。

**Comment by giovanninardini** [comment]
> > 参数控制带宽。它是分配给该特定运营商的资源块数。例如，对于命理为 0 的 4G 和 5G，“50 RUB”表示 10MHz 带宽，“100 RUB”表示 20MHz 带宽，依此类推。
> 
> thanks This means that the RB of each 4G and 5G BS has the same resource; Each RB occupies 0.2Mhz。

according to the 3GPP standard, one RB occupies 180KHz (with 4G and 5G with numerology index 0)

**Comment by shashini-w** [comment]
> > dear author I want to know where to set the subbandwidth parameters of the eNodeB and gNodeB; I want to set different bandwidth for two types of BS； for example, *.carrierAggregation.componentCarrier[0].carrierFrequency=2GHz *.carrierAggregation.componentCarrier[0].numBands=50 *.carrierAggregation.componentCarrier[1].carrierFrequency=28GHz *.carrierAggregation.componentCarrier[1].numBands=50 and Each vehicle（0） can obtain 10Mhz bandwidth； Each vehicle（1） can obtain 100Mhz bandwidth；
> 
> The _numBands_ parameter controls the bandwidth. It is the number of Resource Blocks assigned to that specific carrier. For example, with 4G and 5G with numerology 0, "50 RBs" mean 10MHz bandwidth, "100 RBs" mean 20MHz bandwidth, and so on.

Dear Mr. @giovanninardini,

Could you please explain how this relationship between RBs and the Bandwidth (num bands/5 = Bandwidth in MHz) is derived?
I want to use a different numerology and as you have told this is only valid for numerology 0, I want to know how to calculate the Bandwidth in that case based on the num bands.

Because I tried to rebuild the relation and for example, if I have set num bands =50 with numerology 0, then 
No. of RBs = 50 
No. of subcarriers = 50 * 12 = 600. 
Transmission Bandwidth = No.of subcarriers * subcarrier spacing = 600*15 kHz = 9 MHz. 
Is the guard band set to be 500kHz to make the channel Bandwidth = 10MHz ? (I suppose in your explanation you meant channel Bandwidth is 10MHz)

**Comment by giovanninardini** [comment]
Hello,

Your calculations are correct. 
You should consider 10% of the bandwidth as reserved for guard bands (1MHz in case of 10 MHz channel bandwidth).

**Comment by shashini-w** [comment]
> Hello,
> 
> Your calculations are correct. You should consider 10% of the bandwidth as reserved for guard bands (1MHz in case of 10 MHz channel bandwidth).

Thank you! 
So this means the generalized relationship is :  Channel Bandwidth in MHz = (num bands/5) * 2^numerology index 
with 10% of the bandwidth reserved for guard bands
