### ISSUE TITLE
Build fails with OMNeT++ 6.0 x64, inet-4.4.0 running on Win7

### ISSUE THREAD

**Issue by B0GDAN** [Unipisa/Simu5G#82]
08:48:55 **** Build of configuration gcc-debug for project simu5g ****
make MODE=debug -j2 all 
make[1]: Entering directory '/c/omnetpp-6.0/samples/simu5g/src'
MSGC: apps/alert/AlertPacket.msg
MSGC: apps/burst/BurstPacket.msg
apps/alert/AlertPacket.msg:16: Error: cannot resolve import 'inet.common.INETDefs'
apps/alert/AlertPacket.msg:17: Error: cannot resolve import 'inet.common.packet.chunk.Chunk'
apps/alert/AlertPacket.msg:20: Error: 'AlertPacket': unknown base class 'inet::FieldsChunk'
opp_msgtool: error in 1 file(s)
make[1]: *** [Makefile:417: apps/alert/AlertPacket_m.h] Error 1
make[1]: *** Waiting for unfinished jobs....
apps/burst/BurstPacket.msg:12: Error: cannot resolve import 'inet.common.INETDefs'
apps/burst/BurstPacket.msg:13: Error: cannot resolve import 'inet.common.packet.chunk.Chunk'
apps/burst/BurstPacket.msg:20: Error: 'BurstPacket': unknown base class 'inet::FieldsChunk'
opp_msgtool: error in 1 file(s)
make[1]: *** [Makefile:417: apps/burst/BurstPacket_m.h] Error 1
make[1]: Leaving directory '/c/omnetpp-6.0/samples/simu5g/src'
make: *** [Makefile:2: all] Error 2
"make MODE=debug -j2 all" terminated with exit code 2. Build might be incomplete.

08:49:41 Build Failed. 10 errors, 0 warnings. (took 45s.932ms)

**Comment by B0GDAN** [comment]
OMNeT++ Integrated Development Environment
Version: 6.0, Build id: 220413-71d8fab425
Copyright (C) 2005-2022 OpenSim Ltd.
OS: Windows 7, v.6.1, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.1+12
Java version: 17.0.1

**Comment by Sable911** [comment]
I just solved the same question by setting simu5g's Project Preference in its properties, you can find it by right clicking Simu5G folder in Project Explorer. Hope this can help you.
