### ISSUE TITLE
MEC Service info extraction vs. throughput

### ISSUE THREAD

**Issue by EstefaniaCC** [Unipisa/Simu5G#91]
Hi,

Is there a way to show (either output to file, or vector to plot) the information gathered from MEC services? For instance, in some examples, the RNI or the Location service is used. In which manner the various locations registered by the UE or the info from the RNI for each UE can be seen?

Is it possible to establish a relationship between that info and the throughput of the MEC application?

Thanks a lot.

**Comment by giovanninardini** [comment]
Hi,

sorry for the delay. 
MEC services expose information to MEC apps, so the task of visualizing, recording, logging, etc. the information retrieved by such services should be performed by MEC apps themselves.
In other words, when you implement your own MEC app that gathers some info from one or more MEC services, you are responsible to implement the code to view the information.

Best regards.
Giovanni

**Comment by EstefaniaCC** [comment]
Hi Giovanni, 

Is there an example already I can look at?

Thanks.
