### ISSUE TITLE
Simu5G user measurement report used for handover

### ISSUE THREAD

**Issue by eliehaber90** [Unipisa/Simu5G#92]
Hi,

I understand Simu5G uses the SINR value to trigger the handover procedure. However, I want to ask why the RSRP and RSRQ values are not simulated and used instead. And how difficult is it if I want to add those calculations myself in Simu5G?

Thank you

**Comment by giovanninardini** [comment]
Hi, 

sorry for the delay.
Using SINR to trigger the handover was just our design choice. Actually, the getSINR function used to compute the SINR internally computes the RSRP first, then it "adds" noise and interference.
The LteRealisticChannelModel also provides a function called getRsrp(), maybe that can help you.

Best regards.
Giovanni

**Comment by eliehaber90** [comment]
Ok thanks for the information.
