### ISSUE TITLE
Question about retransmission

### ISSUE THREAD

**Issue by Jiacheng188** [Unipisa/Simu5G#95]
Hello,
I was debugging the source code when i found that the scheduler's method "scheduler->updateSchedulingInfo()" contains no code.
As this method is called after scheduling _scheduleRacRequests_ and _scheduleRetransmissions_, I guess Simu5g model retransmission in other bands which is not used by current carrier, Am I right？

**Comment by giovanninardini** [comment]
Hello,

Simu5G models RAC requests and retransmissions in the same carrier as new transmissions.
Scheduling of new transmissions is performed by the _schedule()_ function, which is invoked after _scheduleRacRequests()_, _scheduleRetransmissions()_ and _updateSchedulingInfo()_.

The _updateSchedulingInfo()_ contains no code in the base LteScheduler class, but it can be redefined by derived modules, if needed. For example, the _LteDrr_ module redefines the _updateSchedulingInfo()_ function.

Best regards.
Giovanni

**Comment by Jiacheng188** [comment]
Thank you!
