### ISSUE TITLE
get UserControlInfo at the application layer

### ISSUE THREAD

**Issue by gehirndienst** [Unipisa/Simu5G#98]
Hello,

I model a learning environment for UDP data transmission between dynamic UEs and a static server. I would like to be able to know the channel information at the application layer, i.e., inside my UDP app. As far as I could get, the only broadcasted statistics so far are CQI and SINR signals from `LtePhy `and `LteNic `modules. However, to compute e.g., SINR in `LteRealisticChannelModel`, one needs to pass an `LteAirFrame` and `UserControlInfo` as parameters, which are obtained in `handleAirFrame` methods from `LtePhy*` modules via getting the `LteAirFrame` tag.

Unfortunately, as one can see, this `UserControlInfo` object exists only within the scope of `::handleAirFrame` and is published only in a form of CQI signal. I wonder if there is a way to get this object or at least its fields somehow without extending `LtePhyUe` module? Thanks!

Best
Nikita

**Comment by giovanninardini** [comment]
Hello,

if I understand your problem, I think one option could be able to _emit_ the whole object as a signal, like you do with statistics.
For example, you could declare a new signal in the NED file, and emit the object (with the emit() function) in the handleAirFrame() function using that signal. In the application, you could listen to the signal and catch it when it is emitted.
Please refer to the OMNeT++ manual for more information: https://doc.omnetpp.org/omnetpp/manual/#sec:simple-modules:signals

Best regards.
Giovanni
